'use client'
// ═══════════════════════════════════════════════════════════════════
// /CallScheduler/[id] — 상세 (캘린더 + 분석 + 배포)
// ═══════════════════════════════════════════════════════════════════
import { useEffect, useState, use } from 'react'
import Link from 'next/link'
import { useRouter } from 'next/navigation'
import { COLORS, GLASS, BTN, pillStyle } from '@/app/utils/ui-tokens'
// (GLASS / pillStyle 은 actionMsg 패널에서 사용)
import { getAuthHeader } from '@/app/utils/auth-client'
import { CallSchedulerProvider, useCallScheduler } from '../CallSchedulerContext'
import KpiStrip from '../components/KpiStrip'
import ScheduleGrid from '../components/ScheduleGrid'
// PR-2EE (2026-05-04): ComposeMode 폐기 — 셋팅 → 자동 생성 → 표출/수정 흐름으로 단순화
// import ComposeMode from '../components/ComposeMode'
import DayView from '../components/DayView'
import WeekView from '../components/WeekView'
import AnalyticsDrawer from '../components/AnalyticsDrawer'
import DistributionDialog from '../components/DistributionDialog'
import EmployeeRequestsPanel from '../components/EmployeeRequestsPanel'
import AutoGenerateDialog from '../components/AutoGenerateDialog'
// PR-2QQ-d-1 — 외부 직원 엑셀 업로드 폐기 (워커 셋팅으로 자동 채움)
// import ExternalScheduleDialog from '../components/ExternalScheduleDialog'

export const dynamic = 'force-dynamic'

export default function CallSchedulerDetailPage({
  params,
}: { params: Promise<{ id: string }> }) {
  const { id } = use(params)
  return (
    <CallSchedulerProvider>
      <DetailInner id={id} />
    </CallSchedulerProvider>
  )
}

type ViewMode = 'view' | 'week' | 'day'  // L-1: week 추가

function DetailInner({ id }: { id: string }) {
  const router = useRouter()
  const { detail, loading, error, reload } = useCallScheduler()
  const [distOpen, setDistOpen] = useState(false)
  const [drawerOpen, setDrawerOpen] = useState(false)
  const [mode, setMode] = useState<ViewMode>('view')
  const [moreOpen, setMoreOpen] = useState(false)
  const [statusBusy, setStatusBusy] = useState(false)
  const [actionMsg, setActionMsg] = useState<{ ok: boolean; text: string } | null>(null)
  const [pendingSwapCount, setPendingSwapCount] = useState(0)
  const [pendingLeaveCount, setPendingLeaveCount] = useState(0)
  const [requestsOpen, setRequestsOpen] = useState(false)
  const [autoGenOpen, setAutoGenOpen] = useState(false)
  // L-2 — 본인 워커 ID (있으면 ScheduleGrid「내것만」 토글 활성)
  const [myWorkerId, setMyWorkerId] = useState<string | undefined>(undefined)
  // PR-2QQ-d-1 — 외부 직원 엑셀 업로드 폐기 (워커 셋팅으로 자동 채움)
  // const [externalOpen, setExternalOpen] = useState(false)

  useEffect(() => { reload(id) }, [id, reload])

  // L-2 — 본인 워커 ID fetch (매니저 본인이 워커 등록되어 있으면 강조 가능)
  useEffect(() => {
    let abort = false
    ;(async () => {
      try {
        const auth = await getAuthHeader()
        const res = await fetch('/api/call-scheduler/me?year=2099&month=1', { headers: auth })
        if (abort) return
        if (res.ok) {
          const json = await res.json()
          if (json?.data?.worker?.worker_id) setMyWorkerId(json.data.worker.worker_id)
        }
      } catch { /* graceful — 매니저가 워커 아니면 그냥 비활성 */ }
    })()
    return () => { abort = true }
  }, [])

  // 대기 중 직원 요청 카운트 (PR-2Y swap + PR-2BB leave)
  useEffect(() => {
    let abort = false
    ;(async () => {
      try {
        const auth = await getAuthHeader()
        const [sRes, lRes] = await Promise.all([
          fetch(`/api/call-scheduler/swap-requests?status=pending&schedule_id=${id}`, { headers: auth }),
          fetch(`/api/call-scheduler/leaves?status=pending`, { headers: auth }),
        ])
        const sJ = await sRes.json()
        const lJ = await lRes.json()
        if (!abort) {
          if (sRes.ok) setPendingSwapCount((sJ.data || []).length)
          if (lRes.ok) setPendingLeaveCount((lJ.data || []).length)
        }
      } catch { /* silent */ }
    })()
    return () => { abort = true }
  }, [id, detail?.schedule.updated_at])

  const totalPendingRequests = pendingSwapCount + pendingLeaveCount

  // ESC 로 드로어 / 더보기 닫기
  useEffect(() => {
    const handler = (e: KeyboardEvent) => {
      if (e.key === 'Escape') {
        setDrawerOpen(false)
        setMoreOpen(false)
      }
    }
    window.addEventListener('keydown', handler)
    return () => window.removeEventListener('keydown', handler)
  }, [])

  // 외부 클릭으로 더보기 메뉴 닫기
  useEffect(() => {
    if (!moreOpen) return
    const handler = (e: MouseEvent) => {
      const target = e.target as HTMLElement
      if (!target.closest('[data-more-menu]')) setMoreOpen(false)
    }
    setTimeout(() => document.addEventListener('click', handler), 0)
    return () => document.removeEventListener('click', handler)
  }, [moreOpen])

  const setStatus = async (status: 'draft' | 'published' | 'archived') => {
    setStatusBusy(true)
    setActionMsg(null)
    try {
      const auth = await getAuthHeader()
      const res = await fetch(`/api/call-scheduler/schedules/${id}`, {
        method: 'PATCH',
        headers: { 'Content-Type': 'application/json', ...auth },
        body: JSON.stringify({ status }),
      })
      const json = await res.json()
      if (!res.ok) throw new Error(json?.error || '상태 변경 실패')
      setActionMsg({ ok: true, text: `상태 → ${status === 'published' ? '공지됨' : status === 'draft' ? '초안' : '보관'}` })
      reload(id)
    } catch (e: any) {
      setActionMsg({ ok: false, text: e?.message || '오류' })
    } finally {
      setStatusBusy(false)
    }
  }

  const remove = async () => {
    if (!confirm('이 스케줄과 모든 배정을 삭제합니다. 계속할까요?')) return
    setStatusBusy(true)
    try {
      const auth = await getAuthHeader()
      const res = await fetch(`/api/call-scheduler/schedules/${id}`, {
        method: 'DELETE', headers: auth,
      })
      const json = await res.json()
      if (!res.ok) throw new Error(json?.error || '삭제 실패')
      router.push('/CallScheduler')
    } catch (e: any) {
      setActionMsg({ ok: false, text: e?.message || '삭제 실패' })
      setStatusBusy(false)
    }
  }

  if (loading && !detail) {
    return (
      <div style={{ padding: 40, textAlign: 'center', color: COLORS.textMuted }}>
        로딩 중...
      </div>
    )
  }
  if (error) {
    return (
      <div style={{ padding: 24, maxWidth: 600, margin: '0 auto' }}>
        <div style={{
          padding: 16, borderRadius: 12, background: COLORS.bgRed,
          border: `1px solid ${COLORS.borderRed}`, color: COLORS.danger,
        }}>
          ❌ {error}
        </div>
        <Link href="/CallScheduler" style={{
          display: 'inline-block', marginTop: 12,
          ...BTN.md, background: 'transparent', color: COLORS.textSecondary,
          border: `1px solid ${COLORS.borderFaint}`, textDecoration: 'none',
        }}>← 목록</Link>
      </div>
    )
  }
  if (!detail) return null

  const { schedule, kpi, distributions, workers } = detail
  const statusTone = schedule.status === 'published' ? 'success' : schedule.status === 'draft' ? 'info' : 'neutral'
  const statusLabel = schedule.status === 'published' ? '공지됨' : schedule.status === 'draft' ? '초안' : '보관'

  return (
    <div style={{ padding: '16px 20px', width: '100%' }}>
      {/* 헤더 */}
      <div style={{
        display: 'flex', alignItems: 'center', justifyContent: 'space-between',
        marginBottom: 14, flexWrap: 'wrap', gap: 12,
      }}>
        {/* N-12 — 자체 헤더 제거 (PageTitle 자동), 월 정보는 status pill 만 유지 */}
        <div style={{ display: 'flex', alignItems: 'center', gap: 12 }}>
          <span style={{ fontSize: 14, fontWeight: 700, color: '#0f2440' }}>
            {schedule.year}년 {schedule.month}월
          </span>
          <span style={pillStyle(statusTone)}>{statusLabel}</span>
          {schedule.title && (
            <span style={{ fontSize: 12, color: COLORS.textMuted }}>{schedule.title}</span>
          )}
        </div>
        <div style={{ display: 'flex', gap: 8, alignItems: 'center', position: 'relative' }}>
          {/* 모드 토글 (매트릭스 / 날짜별) — PR-2EE 단순화 */}
          <div style={{
            display: 'inline-flex', borderRadius: 8, overflow: 'hidden',
            border: `1px solid ${COLORS.borderFaint}`,
          }}>
            <button
              type="button"
              onClick={() => setMode('view')}
              style={{
                padding: '6px 14px', fontSize: 12, fontWeight: 700,
                background: mode === 'view' ? COLORS.primary : 'transparent',
                color: mode === 'view' ? '#fff' : COLORS.textSecondary,
                border: 'none', cursor: 'pointer',
              }}
              title="시프트 × 일자 매트릭스 — 클릭/우클릭으로 수정"
            >
              📋 매트릭스
            </button>
            <button
              type="button"
              onClick={() => setMode('week')}
              style={{
                padding: '6px 14px', fontSize: 12, fontWeight: 700,
                background: mode === 'week' ? COLORS.primary : 'transparent',
                color: mode === 'week' ? '#fff' : COLORS.textSecondary,
                border: 'none', cursor: 'pointer',
                borderLeft: `1px solid ${COLORS.borderFaint}`,
              }}
              title="주간 뷰 — 1주 7일 × 슬롯 (좁은 화면)"
            >
              📆 주간
            </button>
            <button
              type="button"
              onClick={() => setMode('day')}
              style={{
                padding: '6px 14px', fontSize: 12, fontWeight: 700,
                background: mode === 'day' ? COLORS.primary : 'transparent',
                color: mode === 'day' ? '#fff' : COLORS.textSecondary,
                border: 'none', cursor: 'pointer',
                borderLeft: `1px solid ${COLORS.borderFaint}`,
              }}
              title="일자별 — 그날의 인원 카드"
            >
              📅 날짜별
            </button>
          </div>

          {/* 핵심 액션 — 배포 */}
          <button
            type="button"
            onClick={() => setDistOpen(true)}
            style={{
              ...BTN.lg, background: COLORS.primary, color: '#fff', border: 'none',
              cursor: 'pointer',
            }}
          >
            ⚡ 배포
          </button>

          {/* 더보기 메뉴 (⋯) */}
          <div data-more-menu style={{ position: 'relative' }}>
            <button
              type="button"
              onClick={() => setMoreOpen(o => !o)}
              style={{
                ...BTN.md,
                background: moreOpen ? COLORS.bgGray
                  : totalPendingRequests > 0 ? COLORS.bgAmber
                  : 'transparent',
                color: totalPendingRequests > 0 ? COLORS.warning : COLORS.textSecondary,
                border: `1px solid ${totalPendingRequests > 0 ? COLORS.borderAmber : COLORS.borderFaint}`,
                cursor: 'pointer', minWidth: 36, textAlign: 'center',
                position: 'relative',
              }}
              title={totalPendingRequests > 0
                ? `직원 요청 ${totalPendingRequests}건 대기 (휴가 ${pendingLeaveCount} · 교체 ${pendingSwapCount})`
                : '더보기'}
            >
              ⋯
              {totalPendingRequests > 0 && (
                <span style={{
                  position: 'absolute', top: -6, right: -6,
                  background: COLORS.danger, color: '#fff',
                  fontSize: 9, fontWeight: 800, padding: '1px 5px', borderRadius: 999,
                  minWidth: 14, textAlign: 'center',
                }}>{totalPendingRequests}</span>
              )}
            </button>
            {moreOpen && (
              <div style={{
                position: 'absolute', top: '100%', right: 0, marginTop: 4,
                ...GLASS.L4, borderRadius: 10, padding: 6, minWidth: 200,
                boxShadow: '0 8px 24px rgba(0,0,0,0.12)',
                zIndex: 100, display: 'flex', flexDirection: 'column', gap: 2,
              }}>
                {/* 공지/초안 토글 */}
                {schedule.status === 'draft' && (
                  <MenuItem
                    icon="✓"
                    label="공지됨으로 변경"
                    sub="직원에게 영구 링크로 노출됨"
                    tone="success"
                    disabled={statusBusy}
                    onClick={() => { setMoreOpen(false); setStatus('published') }}
                  />
                )}
                {schedule.status === 'published' && (
                  <MenuItem
                    icon="←"
                    label="초안으로 되돌리기"
                    sub="직원 노출 차단"
                    disabled={statusBusy}
                    onClick={() => { setMoreOpen(false); setStatus('draft') }}
                  />
                )}
                {/* 자동 생성 (PR-2EE — ComposeMode 폐기 후 여기로 이동) */}
                <MenuItem
                  icon="✨"
                  label="자동 생성"
                  sub="그룹 셋팅 + 휴가 반영 일괄 적용"
                  tone="success"
                  onClick={() => { setMoreOpen(false); setAutoGenOpen(true) }}
                />
                {/* PR-2QQ-d-1: 외부 직원 엑셀 업로드 폐기 — 워커 셋팅 (priority/패턴/비선호) 으로 자동 채움 */}
                {/* 직원 요청 통합 (PR-2BB + PR-2Y) */}
                <MenuItem
                  icon="📥"
                  label={`직원 요청${totalPendingRequests > 0 ? ` (${totalPendingRequests})` : ''}`}
                  sub={totalPendingRequests > 0
                    ? `휴가 ${pendingLeaveCount} · 교체 ${pendingSwapCount} 대기`
                    : '대기 요청 없음'}
                  tone={totalPendingRequests > 0 ? 'success' : undefined}
                  onClick={() => { setMoreOpen(false); setRequestsOpen(true) }}
                />
                {/* 분석 토글 */}
                <MenuItem
                  icon="📊"
                  label={drawerOpen ? '분석 닫기' : '분석 / 배포 이력'}
                  sub="인당 KPI · 배포 기록"
                  active={drawerOpen}
                  onClick={() => { setMoreOpen(false); setDrawerOpen(o => !o) }}
                />
                <div style={{ height: 1, background: COLORS.borderFaint, margin: '4px 0' }} />
                {/* 삭제 — 본 월 한정 위험 작업 */}
                <MenuItem
                  icon="🗑"
                  label="삭제"
                  sub="배정·배포 이력 모두 제거"
                  tone="danger"
                  disabled={statusBusy}
                  onClick={() => { setMoreOpen(false); remove() }}
                />
              </div>
            )}
          </div>
        </div>
      </div>

      {actionMsg && (
        <div style={{
          ...GLASS.L3,
          background: actionMsg.ok ? COLORS.bgGreen : COLORS.bgRed,
          border: `1px solid ${actionMsg.ok ? COLORS.borderGreen : COLORS.borderRed}`,
          borderRadius: 8, padding: '8px 14px', marginBottom: 12,
          display: 'flex', alignItems: 'center', justifyContent: 'space-between',
        }}>
          <div style={{
            fontSize: 13, fontWeight: 700,
            color: actionMsg.ok ? COLORS.success : COLORS.danger,
          }}>
            {actionMsg.ok ? '✅ ' : '❌ '}{actionMsg.text}
          </div>
          <button onClick={() => setActionMsg(null)} style={{
            background: 'transparent', border: 'none',
            color: COLORS.textMuted, cursor: 'pointer', fontSize: 14,
          }}>×</button>
        </div>
      )}

      {/* KPI */}
      <div style={{ marginBottom: 14 }}>
        <KpiStrip kpi={kpi} />
      </div>

      {/* 메인 — 빈 상태 가이드 또는 모드별 분기 (PR-2EE 단순화) */}
      {detail.assignments.length === 0 ? (
        <EmptyScheduleGuide onAutoGenerate={() => setAutoGenOpen(true)} />
      ) : (
        <>
          {mode === 'view' && <ScheduleGrid detail={detail} onChanged={() => reload(id)} myWorkerId={myWorkerId} />}
          {mode === 'week' && <WeekView detail={detail} />}
          {mode === 'day' && <DayView detail={detail} />}
        </>
      )}

      {/* 분석 드로어 (토글) */}
      <AnalyticsDrawer
        open={drawerOpen}
        onClose={() => setDrawerOpen(false)}
        kpi={kpi}
        distributions={distributions}
      />

      <DistributionDialog
        open={distOpen}
        onClose={() => setDistOpen(false)}
        scheduleId={id}
        workers={workers}
        onCompleted={() => reload(id)}
      />

      <EmployeeRequestsPanel
        open={requestsOpen}
        onClose={() => setRequestsOpen(false)}
        scheduleId={id}
        onChanged={() => reload(id)}
      />

      <AutoGenerateDialog
        open={autoGenOpen}
        onClose={() => setAutoGenOpen(false)}
        scheduleId={id}
        onCompleted={() => reload(id)}
        workers={detail?.workers}
        slots={detail?.slots}
      />

      {/* PR-2QQ-d-1: ExternalScheduleDialog 폐기 — 워커 셋팅으로 통합 */}
    </div>
  )
}

// ── 빈 스케줄 가이드 (PR-2EE) ────────────────────────────────────
function EmptyScheduleGuide({ onAutoGenerate }: { onAutoGenerate: () => void }) {
  return (
    <div style={{
      ...GLASS.L4, borderRadius: 16, padding: '60px 32px',
      textAlign: 'center', display: 'flex', flexDirection: 'column',
      alignItems: 'center', gap: 16,
    }}>
      <div style={{ fontSize: 48 }}>📅</div>
      <div>
        <div style={{ fontSize: 18, fontWeight: 800, color: COLORS.textPrimary }}>
          아직 배정된 시프트가 없습니다
        </div>
        <div style={{ fontSize: 13, color: COLORS.textMuted, marginTop: 6, lineHeight: 1.6 }}>
          그룹 · 시프트 · 직원 · 휴가를 <Link href="/CallScheduler/settings" style={{ color: COLORS.info, textDecoration: 'none', fontWeight: 700 }}>⚙️ 설정</Link>에서 등록한 후<br />
          <strong>자동 생성</strong>으로 한 번에 채우세요. 이후 셀 클릭/우클릭으로 미세 조정.
        </div>
      </div>
      <button type="button" onClick={onAutoGenerate}
              style={{
                ...BTN.lg, background: '#7c3aed', color: '#fff', border: 'none',
                fontSize: 15, padding: '14px 28px', cursor: 'pointer',
              }}>
        ✨ 자동 생성 시작
      </button>
      <div style={{ fontSize: 11, color: COLORS.textMuted, marginTop: 4 }}>
        그룹 패턴 + 휴가 반영해서 한 달을 한 번에 채웁니다.
      </div>
    </div>
  )
}

// ── 더보기 메뉴 아이템 ─────────────────────────────────────────────
function MenuItem({
  icon, label, sub, onClick, href, active, disabled, tone,
}: {
  icon: string
  label: string
  sub?: string
  onClick?: () => void
  href?: string
  active?: boolean
  disabled?: boolean
  tone?: 'success' | 'danger'
}) {
  const color = tone === 'danger' ? COLORS.danger
    : tone === 'success' ? COLORS.success
    : active ? COLORS.info
    : COLORS.textPrimary
  const bg = active ? COLORS.bgBlue : 'transparent'
  const hoverBg = tone === 'danger' ? COLORS.bgRed
    : tone === 'success' ? COLORS.bgGreen
    : COLORS.bgGray
  const content = (
    <>
      <span style={{ fontSize: 14, width: 18, textAlign: 'center' }}>{icon}</span>
      <div style={{ flex: 1 }}>
        <div style={{ fontSize: 12, fontWeight: 700, color }}>{label}</div>
        {sub && <div style={{ fontSize: 10, color: COLORS.textMuted }}>{sub}</div>}
      </div>
    </>
  )
  const baseStyle: React.CSSProperties = {
    display: 'flex', alignItems: 'center', gap: 8,
    padding: '6px 10px', borderRadius: 6,
    background: bg,
    border: 'none', cursor: disabled ? 'not-allowed' : 'pointer',
    opacity: disabled ? 0.5 : 1,
    width: '100%', textAlign: 'left',
    textDecoration: 'none',
    transition: 'background 0.15s',
  }
  if (href) {
    return (
      <Link href={href} style={baseStyle}
            onMouseEnter={(e) => { e.currentTarget.style.background = hoverBg }}
            onMouseLeave={(e) => { e.currentTarget.style.background = bg }}>
        {content}
      </Link>
    )
  }
  return (
    <button type="button" onClick={onClick} disabled={disabled} style={baseStyle}
            onMouseEnter={(e) => { if (!disabled) e.currentTarget.style.background = hoverBg }}
            onMouseLeave={(e) => { e.currentTarget.style.background = bg }}>
      {content}
    </button>
  )
}
