'use client'
// ═══════════════════════════════════════════════════════════════════
// AutoGenerateDialog — 자동 생성 모달
//   1) 옵션 선택 (overwrite / clear / skip-holidays / mark-leaves)
//   2) [미리보기] → 계획 요약 + 그룹별 통계
//   3) [실제 적용] → INSERT/UPDATE 실행
// ═══════════════════════════════════════════════════════════════════
import { useState, useEffect } from 'react'
import { COLORS, GLASS, BTN, pillStyle } from '@/app/utils/ui-tokens'
import { getAuthHeader } from '@/app/utils/auth-client'

interface Props {
  open: boolean
  onClose: () => void
  scheduleId: string
  onCompleted: () => void
}

// PR-2SS-b/c/d — Warning 타입 다중
type Warning =
  | { type: 'missing'; group_id: string; group_name: string; date: string; missing: number }
  | { type: 'next_day_block'; worker_id: string; date: string; blocked_slot_id: string; blocking_hours: number; prev_end_date: string }
  | { type: 'time_conflict'; worker_id: string; date: string; slot_a: string; slot_b: string }
  | { type: 'consec_limit'; worker_id: string; date: string; slot_id: string; limit: number }
  | { type: 'slot_blocked'; worker_id: string; date: string; slot_id: string }
  // PR-2SS-d revert — seniority_short 폐기
  | { type: 'group_skip'; worker_id: string; group_id: string; date: string; reason: string | null }

interface Summary {
  mode: 'preview' | 'apply'
  total_plan: number
  to_insert: number
  to_update: number
  skip_existing: number
  skip_holiday: number
  skip_no_member: number
  holidays_excluded: number
  leaves_marked: number
  by_group: Record<string, { generated: number; skipped: number }>
  by_date: Record<string, { generated: number }>
  // PR-2QQ-d-3 → PR-2SS-b/c — 경고 다중 타입
  warnings?: Warning[]
  warning_count?: number
  warn_by_type?: {
    missing: number
    next_day_block: number
    time_conflict: number
    consec_limit?: number
    slot_blocked?: number
    group_skip?: number  // PR-2SS-h-1
  }
  use_priority?: boolean
  enforce_min_coverage?: boolean
}

export default function AutoGenerateDialog({ open, onClose, scheduleId, onCompleted }: Props) {
  // 본 회사 (24/365) 디폴트: skipHolidays=false (공휴일도 누군가 근무)
  const [overwrite, setOverwrite] = useState(false)
  const [clearFirst, setClearFirst] = useState(false)
  const [skipHolidays, setSkipHolidays] = useState(false)
  const [markLeaves, setMarkLeaves] = useState(true)
  // PR-2QQ-d-3 새 옵션
  const [usePriority, setUsePriority] = useState(true)
  const [enforceMinCoverage, setEnforceMinCoverage] = useState(true)
  const [busy, setBusy] = useState(false)
  const [summary, setSummary] = useState<Summary | null>(null)
  const [error, setError] = useState<string | null>(null)
  const [applied, setApplied] = useState(false)

  const run = async (mode: 'preview' | 'apply') => {
    setBusy(true); setError(null)
    if (mode === 'preview') setApplied(false)
    try {
      const auth = await getAuthHeader()
      const res = await fetch(`/api/call-scheduler/schedules/${scheduleId}/auto-generate`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json', ...auth },
        body: JSON.stringify({
          mode,
          overwrite_existing: overwrite,
          clear_first: clearFirst,
          skip_holidays: skipHolidays,
          mark_leaves: markLeaves,
          use_priority: usePriority,
          enforce_min_coverage: enforceMinCoverage,
        }),
      })
      const json = await res.json()
      if (!res.ok) throw new Error(json?.error || '실행 실패')
      setSummary(json.data.summary)
      if (mode === 'apply') {
        setApplied(true)
        onCompleted()
      }
    } catch (e: any) {
      setError(e?.message || '오류')
    } finally {
      setBusy(false)
    }
  }

  // 모달 열림 + 옵션 변경 시 자동 미리보기 (debounce 300ms)
  useEffect(() => {
    if (!open || applied) return
    const timer = setTimeout(() => {
      run('preview')
    }, 300)
    return () => clearTimeout(timer)
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [open, overwrite, clearFirst, skipHolidays, markLeaves, usePriority, enforceMinCoverage])

  if (!open) return null

  const close = () => {
    setSummary(null); setError(null); setApplied(false)
    onClose()
  }

  return (
    <div onClick={close}
         style={{
           position: 'fixed', inset: 0, background: 'rgba(0,0,0,0.4)',
           display: 'flex', alignItems: 'center', justifyContent: 'center', zIndex: 1000,
         }}>
      <div onClick={(e) => e.stopPropagation()}
           style={{
             ...GLASS.L4, width: 640, maxWidth: '94vw', maxHeight: '90vh',
             borderRadius: 16, padding: 22, overflowY: 'auto',
             display: 'flex', flexDirection: 'column', gap: 14,
           }}>
        {/* 헤더 */}
        <div>
          <div style={{ fontSize: 18, fontWeight: 800, color: COLORS.textPrimary }}>
            ✨ 자동 생성
          </div>
          <div style={{ fontSize: 12, color: COLORS.textMuted, marginTop: 2 }}>
            그룹 패턴 + 휴일 + 연차를 활용해 한 달 스케줄을 자동으로 채웁니다.
          </div>
        </div>

        {/* 옵션 */}
        <div style={{
          ...GLASS.L1, borderRadius: 8, padding: 12,
          display: 'flex', flexDirection: 'column', gap: 8,
        }}>
          <CheckRow checked={skipHolidays} onChange={setSkipHolidays}
                    label="🏖 휴일 자동 제외"
                    sub="cs_holidays 의 exclude_auto=1 일자는 배정 안 함" />
          <CheckRow checked={markLeaves} onChange={setMarkLeaves}
                    label="📋 연차 자동 표시"
                    sub="해당 워커 연차 일자에 휴무/반차 자동 적용" />
          <CheckRow checked={overwrite} onChange={setOverwrite}
                    label="✏️ 기존 셀 덮어쓰기"
                    sub="이미 배정된 셀도 자동 생성 결과로 변경 (위험)"
                    warn={overwrite} />
          <CheckRow checked={clearFirst} onChange={(v) => { setClearFirst(v); if (v) setOverwrite(true) }}
                    label="🗑 시작 전 모두 삭제"
                    sub="기존 모든 배정 DELETE 후 새로 채움 (가장 위험, manual_lock 보존)"
                    warn={clearFirst} danger={clearFirst} />
          <div style={{ height: 1, background: COLORS.borderFaint, margin: '4px 0' }} />
          {/* PR-2QQ-d-3 새 옵션 */}
          <CheckRow checked={usePriority} onChange={setUsePriority}
                    label="🎯 우선순위 + 균등 분배"
                    sub="P1/P2/P3 + 비선호 요일 + cycle 패턴 + 금/일 균등" />
          <CheckRow checked={enforceMinCoverage} onChange={setEnforceMinCoverage}
                    label="⚖️ 그룹 최소 인원 적용"
                    sub="cs_group_min_coverage 의 요일별 최소 인원 충족" />
        </div>

        {/* 결과 요약 */}
        {summary && (
          <div style={{
            ...GLASS.L3,
            background: applied ? COLORS.bgGreen : COLORS.bgBlue,
            border: `1px solid ${applied ? COLORS.borderGreen : COLORS.borderBlue}`,
            borderRadius: 12, padding: 14,
          }}>
            <div style={{
              fontSize: 13, fontWeight: 800, marginBottom: 10,
              color: applied ? COLORS.success : COLORS.info,
            }}>
              {applied ? '✅ 적용 완료' : '🔍 미리보기 (실제 변경 없음)'}
            </div>
            <div style={{
              display: 'grid', gridTemplateColumns: 'repeat(3, 1fr)', gap: 8,
              marginBottom: 10,
            }}>
              <Tile label="신규" value={summary.to_insert} tone="success" />
              <Tile label="갱신" value={summary.to_update} tone="info" />
              <Tile label="건너뜀" value={summary.skip_existing + summary.skip_holiday + summary.skip_no_member} tone="neutral" />
            </div>
            <div style={{ fontSize: 11, color: COLORS.textMuted, marginBottom: 6 }}>
              · 휴일 제외: {summary.skip_holiday} 셀
              · 연차 표시: {summary.leaves_marked}건
              · 기존 보존: {summary.skip_existing} 셀
              · 멤버 없음 그룹: {summary.skip_no_member} 셀
            </div>
            {Object.keys(summary.by_group).length > 0 && (
              <div style={{ marginTop: 10, paddingTop: 8, borderTop: `1px solid ${COLORS.borderFaint}` }}>
                <div style={{ fontSize: 11, fontWeight: 700, color: COLORS.textSecondary, marginBottom: 4 }}>
                  그룹별 결과
                </div>
                <div style={{ display: 'flex', flexWrap: 'wrap', gap: 4 }}>
                  {Object.entries(summary.by_group).map(([gid, s]) => (
                    <span key={gid} style={pillStyle(s.generated > 0 ? 'success' : 'neutral')}>
                      {s.generated}생성 / {s.skipped}skip
                    </span>
                  ))}
                </div>
              </div>
            )}
            {/* PR-2QQ-d-3 → PR-2SS-b — 경고 다중 타입 */}
            {summary.warning_count != null && summary.warning_count > 0 && (
              <div style={{
                marginTop: 10, padding: '8px 10px', borderRadius: 6,
                background: COLORS.bgRed, border: `1px solid ${COLORS.borderRed}`,
              }}>
                <div style={{ fontSize: 11, fontWeight: 800, color: COLORS.danger, marginBottom: 4 }}>
                  ⚠ 자동 생성 경고 ({summary.warning_count}건)
                </div>
                {summary.warn_by_type && (
                  <div style={{ display: 'flex', gap: 6, flexWrap: 'wrap', marginBottom: 6 }}>
                    {summary.warn_by_type.missing > 0 && (
                      <span style={pillStyle('warning')}>
                        🪫 인원 부족 {summary.warn_by_type.missing}건
                      </span>
                    )}
                    {summary.warn_by_type.next_day_block > 0 && (
                      <span style={pillStyle('danger')}>
                        🌙 익일 휴식 위반 {summary.warn_by_type.next_day_block}건
                      </span>
                    )}
                    {summary.warn_by_type.time_conflict > 0 && (
                      <span style={pillStyle('danger')}>
                        ⏱ 시간 겹침 {summary.warn_by_type.time_conflict}건
                      </span>
                    )}
                    {(summary.warn_by_type.consec_limit ?? 0) > 0 && (
                      <span style={pillStyle('warning')}>
                        📅 연속 한도 {summary.warn_by_type.consec_limit}건
                      </span>
                    )}
                    {(summary.warn_by_type.slot_blocked ?? 0) > 0 && (
                      <span style={pillStyle('neutral')}>
                        🚫 슬롯 거부 {summary.warn_by_type.slot_blocked}건
                      </span>
                    )}
                    {(summary.warn_by_type.group_skip ?? 0) > 0 && (
                      <span style={pillStyle('warning')}>
                        🛌 그룹 회피 {summary.warn_by_type.group_skip}건
                      </span>
                    )}
                  </div>
                )}
                <div style={{ fontSize: 10, color: COLORS.textSecondary, maxHeight: 100, overflowY: 'auto' }}>
                  {summary.warnings?.slice(0, 12).map((w, i) => {
                    if (w.type === 'missing') {
                      return <div key={i}>🪫 {w.group_name} · {w.date}: {w.missing}명 부족</div>
                    }
                    if (w.type === 'next_day_block') {
                      return (
                        <div key={i}>
                          🌙 {w.date}: 워커 {w.worker_id.slice(0, 8)}… 직전 슬롯 {w.prev_end_date} 종료 후 {w.blocking_hours}h 미충족 → 후보 제외
                        </div>
                      )
                    }
                    if (w.type === 'time_conflict') {
                      return (
                        <div key={i}>
                          ⏱ {w.date}: 워커 {w.worker_id.slice(0, 8)}… 두 슬롯 시간 겹침 ({w.slot_a.slice(0, 8)}… × {w.slot_b.slice(0, 8)}…)
                        </div>
                      )
                    }
                    if (w.type === 'consec_limit') {
                      return (
                        <div key={i}>
                          📅 {w.date}: 워커 {w.worker_id.slice(0, 8)}… 연속 {w.limit}일 한도 도달 → 후보 제외 (슬롯 {w.slot_id.slice(0, 8)}…)
                        </div>
                      )
                    }
                    if (w.type === 'slot_blocked') {
                      return (
                        <div key={i}>
                          🚫 {w.date}: 워커 {w.worker_id.slice(0, 8)}… 슬롯 거부 명단 (슬롯 {w.slot_id.slice(0, 8)}…)
                        </div>
                      )
                    }
                    if (w.type === 'group_skip') {
                      return (
                        <div key={i}>
                          🛌 {w.date}: 워커 {w.worker_id.slice(0, 8)}… 그룹 회피일{w.reason ? ` — ${w.reason}` : ''}
                        </div>
                      )
                    }
                    return null
                  })}
                  {summary.warning_count > 12 && (
                    <div style={{ color: COLORS.textMuted, marginTop: 2 }}>
                      ... 외 {summary.warning_count - 12}건
                    </div>
                  )}
                </div>
              </div>
            )}
          </div>
        )}

        {error && (
          <div style={{
            padding: '8px 12px', borderRadius: 8,
            background: COLORS.bgRed, border: `1px solid ${COLORS.borderRed}`,
            color: COLORS.danger, fontSize: 13,
          }}>❌ {error}</div>
        )}

        {/* 액션 */}
        <div style={{ display: 'flex', justifyContent: 'space-between', gap: 8, marginTop: 4 }}>
          <button type="button" onClick={close} disabled={busy} style={{
            ...BTN.md, background: 'transparent', color: COLORS.textSecondary,
            border: `1px solid ${COLORS.borderFaint}`, cursor: 'pointer',
          }}>
            {applied ? '닫기' : '취소'}
          </button>
          <div style={{ display: 'flex', gap: 8 }}>
            <button type="button" onClick={() => run('preview')} disabled={busy} style={{
              ...BTN.sm, background: 'transparent', color: COLORS.info,
              border: `1px solid ${COLORS.borderBlue}`, cursor: busy ? 'not-allowed' : 'pointer',
            }}>
              {busy ? '계산 중...' : '🔄 다시 계산'}
            </button>
            {(() => {
              // summary 가 0건이면 비활성 (생성 의미 없음). 그 외는 활성
              const noChange = summary && (summary.to_insert + summary.to_update === 0)
              const dis = busy || applied || !!noChange
              return (
                <button type="button"
                        onClick={() => run('apply')}
                        disabled={dis}
                        style={{
                          ...BTN.lg,
                          background: clearFirst ? COLORS.danger : COLORS.success,
                          color: '#fff', border: 'none',
                          cursor: dis ? 'not-allowed' : 'pointer',
                          opacity: dis ? 0.5 : 1,
                        }}
                        title={noChange ? '변경 사항 없음' : ''}>
                  {applied ? '✅ 적용 완료'
                    : busy ? '진행 중...'
                    : clearFirst ? '🗑 초기화 + 적용'
                    : !summary ? '✨ 적용'
                    : `✨ ${summary.to_insert + summary.to_update}건 적용`}
                </button>
              )
            })()}
          </div>
        </div>
        {busy && !summary && (
          <div style={{
            fontSize: 11, color: COLORS.textMuted, textAlign: 'center', marginTop: -4,
          }}>
            ⏳ 자동 미리보기 중...
          </div>
        )}
        {!busy && !summary && !error && !applied && (
          <div style={{
            fontSize: 11, color: COLORS.textMuted, textAlign: 'center', marginTop: -4,
          }}>
            💡 옵션 변경 시 자동으로 다시 계산됩니다.
          </div>
        )}
      </div>
    </div>
  )
}

function CheckRow({ checked, onChange, label, sub, warn, danger }: {
  checked: boolean; onChange: (v: boolean) => void
  label: string; sub: string; warn?: boolean; danger?: boolean
}) {
  return (
    <label style={{
      display: 'flex', alignItems: 'flex-start', gap: 8,
      padding: '6px 8px', borderRadius: 6, cursor: 'pointer',
      background: warn ? (danger ? COLORS.bgRed : COLORS.bgAmber) : 'transparent',
    }}>
      <input type="checkbox" checked={checked}
             onChange={(e) => onChange(e.target.checked)}
             style={{ marginTop: 2 }} />
      <div style={{ flex: 1 }}>
        <div style={{
          fontSize: 13, fontWeight: 700,
          color: danger ? COLORS.danger : warn ? COLORS.warning : COLORS.textPrimary,
        }}>
          {label}
        </div>
        <div style={{ fontSize: 11, color: COLORS.textMuted, marginTop: 2 }}>{sub}</div>
      </div>
    </label>
  )
}

function Tile({ label, value, tone }: {
  label: string; value: number; tone: 'success' | 'info' | 'neutral'
}) {
  const tintMap = {
    success: { bg: COLORS.bgGreen, color: COLORS.success },
    info:    { bg: COLORS.bgBlue,  color: COLORS.info },
    neutral: { bg: COLORS.bgGray,  color: COLORS.textSecondary },
  }[tone]
  return (
    <div style={{
      background: tintMap.bg, borderRadius: 8, padding: '10px 12px', textAlign: 'center',
    }}>
      <div style={{ fontSize: 11, color: COLORS.textSecondary, fontWeight: 600 }}>{label}</div>
      <div style={{ fontSize: 22, fontWeight: 800, color: tintMap.color, lineHeight: 1.1 }}>{value}</div>
    </div>
  )
}
