'use client'
// ═══════════════════════════════════════════════════════════════════
// AutoGenerateDialog — 자동 생성 모달
//   1) 옵션 선택 (overwrite / clear / skip-holidays / mark-leaves)
//   2) [미리보기] → 계획 요약 + 그룹별 통계
//   3) [실제 적용] → INSERT/UPDATE 실행
// ═══════════════════════════════════════════════════════════════════
import { useState } from 'react'
import { COLORS, GLASS, BTN, pillStyle } from '@/app/utils/ui-tokens'
import { getAuthHeader } from '@/app/utils/auth-client'

interface Props {
  open: boolean
  onClose: () => void
  scheduleId: string
  onCompleted: () => void
}

interface Summary {
  mode: 'preview' | 'apply'
  total_plan: number
  to_insert: number
  to_update: number
  skip_existing: number
  skip_holiday: number
  skip_no_member: number
  holidays_excluded: number
  leaves_marked: number
  by_group: Record<string, { generated: number; skipped: number }>
  by_date: Record<string, { generated: number }>
}

export default function AutoGenerateDialog({ open, onClose, scheduleId, onCompleted }: Props) {
  const [overwrite, setOverwrite] = useState(false)
  const [clearFirst, setClearFirst] = useState(false)
  const [skipHolidays, setSkipHolidays] = useState(true)
  const [markLeaves, setMarkLeaves] = useState(true)
  const [busy, setBusy] = useState(false)
  const [summary, setSummary] = useState<Summary | null>(null)
  const [error, setError] = useState<string | null>(null)
  const [applied, setApplied] = useState(false)

  if (!open) return null

  const run = async (mode: 'preview' | 'apply') => {
    setBusy(true); setError(null)
    if (mode === 'preview') setApplied(false)
    try {
      const auth = await getAuthHeader()
      const res = await fetch(`/api/call-scheduler/schedules/${scheduleId}/auto-generate`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json', ...auth },
        body: JSON.stringify({
          mode,
          overwrite_existing: overwrite,
          clear_first: clearFirst,
          skip_holidays: skipHolidays,
          mark_leaves: markLeaves,
        }),
      })
      const json = await res.json()
      if (!res.ok) throw new Error(json?.error || '실행 실패')
      setSummary(json.data.summary)
      if (mode === 'apply') {
        setApplied(true)
        onCompleted()
      }
    } catch (e: any) {
      setError(e?.message || '오류')
    } finally {
      setBusy(false)
    }
  }

  const close = () => {
    setSummary(null); setError(null); setApplied(false)
    onClose()
  }

  return (
    <div onClick={close}
         style={{
           position: 'fixed', inset: 0, background: 'rgba(0,0,0,0.4)',
           display: 'flex', alignItems: 'center', justifyContent: 'center', zIndex: 1000,
         }}>
      <div onClick={(e) => e.stopPropagation()}
           style={{
             ...GLASS.L4, width: 640, maxWidth: '94vw', maxHeight: '90vh',
             borderRadius: 16, padding: 22, overflowY: 'auto',
             display: 'flex', flexDirection: 'column', gap: 14,
           }}>
        {/* 헤더 */}
        <div>
          <div style={{ fontSize: 18, fontWeight: 800, color: COLORS.textPrimary }}>
            ✨ 자동 생성
          </div>
          <div style={{ fontSize: 12, color: COLORS.textMuted, marginTop: 2 }}>
            그룹 패턴 + 휴일 + 연차를 활용해 한 달 스케줄을 자동으로 채웁니다.
          </div>
        </div>

        {/* 옵션 */}
        <div style={{
          ...GLASS.L1, borderRadius: 8, padding: 12,
          display: 'flex', flexDirection: 'column', gap: 8,
        }}>
          <CheckRow checked={skipHolidays} onChange={setSkipHolidays}
                    label="🏖 휴일 자동 제외"
                    sub="cs_holidays 의 exclude_auto=1 일자는 배정 안 함" />
          <CheckRow checked={markLeaves} onChange={setMarkLeaves}
                    label="📋 연차 자동 표시"
                    sub="해당 워커 연차 일자에 휴무/반차 자동 적용" />
          <CheckRow checked={overwrite} onChange={setOverwrite}
                    label="✏️ 기존 셀 덮어쓰기"
                    sub="이미 배정된 셀도 자동 생성 결과로 변경 (위험)"
                    warn={overwrite} />
          <CheckRow checked={clearFirst} onChange={(v) => { setClearFirst(v); if (v) setOverwrite(true) }}
                    label="🗑 시작 전 모두 삭제"
                    sub="기존 모든 배정 DELETE 후 새로 채움 (가장 위험)"
                    warn={clearFirst} danger={clearFirst} />
        </div>

        {/* 결과 요약 */}
        {summary && (
          <div style={{
            ...GLASS.L3,
            background: applied ? COLORS.bgGreen : COLORS.bgBlue,
            border: `1px solid ${applied ? COLORS.borderGreen : COLORS.borderBlue}`,
            borderRadius: 12, padding: 14,
          }}>
            <div style={{
              fontSize: 13, fontWeight: 800, marginBottom: 10,
              color: applied ? COLORS.success : COLORS.info,
            }}>
              {applied ? '✅ 적용 완료' : '🔍 미리보기 (실제 변경 없음)'}
            </div>
            <div style={{
              display: 'grid', gridTemplateColumns: 'repeat(3, 1fr)', gap: 8,
              marginBottom: 10,
            }}>
              <Tile label="신규" value={summary.to_insert} tone="success" />
              <Tile label="갱신" value={summary.to_update} tone="info" />
              <Tile label="건너뜀" value={summary.skip_existing + summary.skip_holiday + summary.skip_no_member} tone="neutral" />
            </div>
            <div style={{ fontSize: 11, color: COLORS.textMuted, marginBottom: 6 }}>
              · 휴일 제외: {summary.skip_holiday} 셀
              · 연차 표시: {summary.leaves_marked}건
              · 기존 보존: {summary.skip_existing} 셀
              · 멤버 없음 그룹: {summary.skip_no_member} 셀
            </div>
            {Object.keys(summary.by_group).length > 0 && (
              <div style={{ marginTop: 10, paddingTop: 8, borderTop: `1px solid ${COLORS.borderFaint}` }}>
                <div style={{ fontSize: 11, fontWeight: 700, color: COLORS.textSecondary, marginBottom: 4 }}>
                  그룹별 결과
                </div>
                <div style={{ display: 'flex', flexWrap: 'wrap', gap: 4 }}>
                  {Object.entries(summary.by_group).map(([gid, s]) => (
                    <span key={gid} style={pillStyle(s.generated > 0 ? 'success' : 'neutral')}>
                      {s.generated}생성 / {s.skipped}skip
                    </span>
                  ))}
                </div>
              </div>
            )}
          </div>
        )}

        {error && (
          <div style={{
            padding: '8px 12px', borderRadius: 8,
            background: COLORS.bgRed, border: `1px solid ${COLORS.borderRed}`,
            color: COLORS.danger, fontSize: 13,
          }}>❌ {error}</div>
        )}

        {/* 액션 */}
        <div style={{ display: 'flex', justifyContent: 'space-between', gap: 8, marginTop: 4 }}>
          <button type="button" onClick={close} disabled={busy} style={{
            ...BTN.md, background: 'transparent', color: COLORS.textSecondary,
            border: `1px solid ${COLORS.borderFaint}`, cursor: 'pointer',
          }}>
            {applied ? '닫기' : '취소'}
          </button>
          <div style={{ display: 'flex', gap: 8 }}>
            <button type="button" onClick={() => run('preview')} disabled={busy} style={{
              ...BTN.md, background: 'transparent', color: COLORS.info,
              border: `1px solid ${COLORS.borderBlue}`, cursor: busy ? 'not-allowed' : 'pointer',
            }}>
              {busy ? '계산 중...' : '🔍 미리보기'}
            </button>
            <button type="button"
                    onClick={() => run('apply')}
                    disabled={busy || !summary || applied}
                    style={{
                      ...BTN.lg,
                      background: clearFirst ? COLORS.danger : COLORS.success,
                      color: '#fff', border: 'none',
                      cursor: busy || !summary || applied ? 'not-allowed' : 'pointer',
                      opacity: !summary || applied ? 0.5 : 1,
                    }}>
              {clearFirst ? '🗑 초기화 + 적용' : '✨ 적용'}
            </button>
          </div>
        </div>
        {!summary && !error && (
          <div style={{
            fontSize: 11, color: COLORS.textMuted, textAlign: 'center', marginTop: -4,
          }}>
            먼저 [미리보기] 로 변경 사항을 확인하세요.
          </div>
        )}
      </div>
    </div>
  )
}

function CheckRow({ checked, onChange, label, sub, warn, danger }: {
  checked: boolean; onChange: (v: boolean) => void
  label: string; sub: string; warn?: boolean; danger?: boolean
}) {
  return (
    <label style={{
      display: 'flex', alignItems: 'flex-start', gap: 8,
      padding: '6px 8px', borderRadius: 6, cursor: 'pointer',
      background: warn ? (danger ? COLORS.bgRed : COLORS.bgAmber) : 'transparent',
    }}>
      <input type="checkbox" checked={checked}
             onChange={(e) => onChange(e.target.checked)}
             style={{ marginTop: 2 }} />
      <div style={{ flex: 1 }}>
        <div style={{
          fontSize: 13, fontWeight: 700,
          color: danger ? COLORS.danger : warn ? COLORS.warning : COLORS.textPrimary,
        }}>
          {label}
        </div>
        <div style={{ fontSize: 11, color: COLORS.textMuted, marginTop: 2 }}>{sub}</div>
      </div>
    </label>
  )
}

function Tile({ label, value, tone }: {
  label: string; value: number; tone: 'success' | 'info' | 'neutral'
}) {
  const tintMap = {
    success: { bg: COLORS.bgGreen, color: COLORS.success },
    info:    { bg: COLORS.bgBlue,  color: COLORS.info },
    neutral: { bg: COLORS.bgGray,  color: COLORS.textSecondary },
  }[tone]
  return (
    <div style={{
      background: tintMap.bg, borderRadius: 8, padding: '10px 12px', textAlign: 'center',
    }}>
      <div style={{ fontSize: 11, color: COLORS.textSecondary, fontWeight: 600 }}>{label}</div>
      <div style={{ fontSize: 22, fontWeight: 800, color: tintMap.color, lineHeight: 1.1 }}>{value}</div>
    </div>
  )
}
