'use client'
// ═══════════════════════════════════════════════════════════════════
// AutoGenerateDialog — 자동 생성 모달 (Phase N-1: 시각화 강화)
//   1) 옵션 선택 (overwrite / clear / skip-holidays / mark-leaves)
//   2) [미리보기] → 계획 요약 + 그룹별 통계 + 워커 이름 + 균형 막대
//   3) [실제 적용] → INSERT/UPDATE 실행
// ═══════════════════════════════════════════════════════════════════
import { useState, useEffect, useMemo } from 'react'
import { COLORS, GLASS, BTN, pillStyle } from '@/app/utils/ui-tokens'
import { TONE_BG, TONE_TEXT } from '../utils/palette'
import { getAuthHeader } from '@/app/utils/auth-client'
import type { Worker, ShiftSlot, ColorTone } from '../utils/types'

interface Props {
  open: boolean
  onClose: () => void
  scheduleId: string
  onCompleted: () => void
  // N-1 — 이름 lookup 용
  workers?: Worker[]
  slots?: ShiftSlot[]
}

// PR-2SS-b/c/d — Warning 타입 다중
type Warning =
  | { type: 'missing'; group_id: string; group_name: string; date: string; missing: number }
  | { type: 'next_day_block'; worker_id: string; date: string; blocked_slot_id: string; blocking_hours: number; prev_end_date: string }
  | { type: 'time_conflict'; worker_id: string; date: string; slot_a: string; slot_b: string }
  | { type: 'consec_limit'; worker_id: string; date: string; slot_id: string; limit: number }
  | { type: 'slot_blocked'; worker_id: string; date: string; slot_id: string }
  // PR-2SS-d revert — seniority_short 폐기
  | { type: 'group_skip'; worker_id: string; group_id: string; date: string; reason: string | null }

interface Summary {
  mode: 'preview' | 'apply'
  total_plan: number
  to_insert: number
  to_update: number
  skip_existing: number
  skip_holiday: number
  skip_no_member: number
  holidays_excluded: number
  leaves_marked: number
  by_group: Record<string, { generated: number; skipped: number }>
  by_date: Record<string, { generated: number }>
  // PR-2QQ-d-3 → PR-2SS-b/c — 경고 다중 타입
  warnings?: Warning[]
  warning_count?: number
  warn_by_type?: {
    missing: number
    next_day_block: number
    time_conflict: number
    consec_limit?: number
    slot_blocked?: number
    group_skip?: number  // PR-2SS-h-1
  }
  use_priority?: boolean
  enforce_min_coverage?: boolean
}

// N-1 — plan row 응답 (워커별 카운트 합산용)
interface PlanRow {
  work_date: string
  shift_slot_id: string
  worker_id: string | null
  special_code: string
  action: string
  group_id: string
  group_name: string
}

export default function AutoGenerateDialog({ open, onClose, scheduleId, onCompleted, workers = [], slots = [] }: Props) {
  // N-1 — 이름 lookup
  const workerName = useMemo(() => {
    const m = new Map<string, { name: string; tone: string }>()
    for (const w of workers) m.set(w.id, { name: w.name, tone: w.color_tone })
    return m
  }, [workers])
  const slotName = useMemo(() => {
    const m = new Map<string, string>()
    for (const s of slots) m.set(s.id, s.code)
    return m
  }, [slots])
  // N-1 — 그룹 이름 lookup (별도 fetch)
  const [groupNameMap, setGroupNameMap] = useState<Map<string, string>>(new Map())
  useEffect(() => {
    if (!open) return
    let abort = false
    ;(async () => {
      try {
        const auth = await getAuthHeader()
        const res = await fetch('/api/call-scheduler/shift-groups', { headers: auth })
        const json = await res.json()
        if (abort || !res.ok) return
        const m = new Map<string, string>()
        for (const g of (json.data || [])) m.set(g.id, g.name)
        setGroupNameMap(m)
      } catch { /* graceful */ }
    })()
    return () => { abort = true }
  }, [open])
  // 짧게 표기 helpers
  const wn = (id: string | undefined | null) => id ? (workerName.get(id)?.name || id.slice(0,8)+'…') : '?'
  const wt = (id: string | undefined | null): ColorTone => id ? ((workerName.get(id)?.tone as ColorTone) || 'none') : 'none'
  const sn = (id: string | undefined | null) => id ? (slotName.get(id) || id.slice(0,8)+'…') : '?'
  const gn = (id: string | undefined | null) => id ? (groupNameMap.get(id) || id.slice(0,8)+'…') : '?'

  // N-1 — plan 응답 → 워커별 카운트 합산
  const [planRows, setPlanRows] = useState<PlanRow[]>([])
  const workerCounts = useMemo(() => {
    const m = new Map<string, number>()
    for (const p of planRows) {
      if (p.worker_id && (p.action === 'insert' || p.action === 'update')) {
        m.set(p.worker_id, (m.get(p.worker_id) || 0) + 1)
      }
    }
    return m
  }, [planRows])
  const maxCount = useMemo(() => {
    let max = 0
    for (const v of workerCounts.values()) if (v > max) max = v
    return max
  }, [workerCounts])
  // 본 회사 (24/365) 디폴트: skipHolidays=false (공휴일도 누군가 근무)
  const [overwrite, setOverwrite] = useState(false)
  const [clearFirst, setClearFirst] = useState(false)
  const [skipHolidays, setSkipHolidays] = useState(false)
  const [markLeaves, setMarkLeaves] = useState(true)
  // PR-2QQ-d-3 새 옵션
  const [usePriority, setUsePriority] = useState(true)
  const [enforceMinCoverage, setEnforceMinCoverage] = useState(true)
  const [busy, setBusy] = useState(false)
  const [summary, setSummary] = useState<Summary | null>(null)
  const [error, setError] = useState<string | null>(null)
  const [applied, setApplied] = useState(false)

  const run = async (mode: 'preview' | 'apply') => {
    setBusy(true); setError(null)
    if (mode === 'preview') setApplied(false)
    try {
      const auth = await getAuthHeader()
      const res = await fetch(`/api/call-scheduler/schedules/${scheduleId}/auto-generate`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json', ...auth },
        body: JSON.stringify({
          mode,
          overwrite_existing: overwrite,
          clear_first: clearFirst,
          skip_holidays: skipHolidays,
          mark_leaves: markLeaves,
          use_priority: usePriority,
          enforce_min_coverage: enforceMinCoverage,
        }),
      })
      const json = await res.json()
      if (!res.ok) throw new Error(json?.error || '실행 실패')
      setSummary(json.data.summary)
      setPlanRows(json.data.plan || [])  // N-1 — 워커별 카운트용
      if (mode === 'apply') {
        setApplied(true)
        onCompleted()
      }
    } catch (e: any) {
      setError(e?.message || '오류')
    } finally {
      setBusy(false)
    }
  }

  // 모달 열림 + 옵션 변경 시 자동 미리보기 (debounce 300ms)
  useEffect(() => {
    if (!open || applied) return
    const timer = setTimeout(() => {
      run('preview')
    }, 300)
    return () => clearTimeout(timer)
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [open, overwrite, clearFirst, skipHolidays, markLeaves, usePriority, enforceMinCoverage])

  if (!open) return null

  const close = () => {
    setSummary(null); setError(null); setApplied(false)
    onClose()
  }

  return (
    <div onClick={close}
         style={{
           position: 'fixed', inset: 0, background: 'rgba(0,0,0,0.4)',
           display: 'flex', alignItems: 'center', justifyContent: 'center', zIndex: 1000,
         }}>
      <div onClick={(e) => e.stopPropagation()}
           style={{
             ...GLASS.L4, width: 640, maxWidth: '94vw', maxHeight: '90vh',
             borderRadius: 16, padding: 22, overflowY: 'auto',
             display: 'flex', flexDirection: 'column', gap: 14,
           }}>
        {/* 헤더 */}
        <div>
          <div style={{ fontSize: 18, fontWeight: 800, color: COLORS.textPrimary }}>
            ✨ 자동 생성
          </div>
          <div style={{ fontSize: 12, color: COLORS.textMuted, marginTop: 2 }}>
            그룹 패턴 + 휴일 + 연차를 활용해 한 달 스케줄을 자동으로 채웁니다.
          </div>
        </div>

        {/* 옵션 */}
        <div style={{
          ...GLASS.L1, borderRadius: 8, padding: 12,
          display: 'flex', flexDirection: 'column', gap: 8,
        }}>
          <CheckRow checked={skipHolidays} onChange={setSkipHolidays}
                    label="🏖 휴일 자동 제외"
                    sub="cs_holidays 의 exclude_auto=1 일자는 배정 안 함" />
          <CheckRow checked={markLeaves} onChange={setMarkLeaves}
                    label="📋 연차 자동 표시"
                    sub="해당 워커 연차 일자에 휴무/반차 자동 적용" />
          <CheckRow checked={overwrite} onChange={setOverwrite}
                    label="✏️ 기존 셀 덮어쓰기"
                    sub="이미 배정된 셀도 자동 생성 결과로 변경 (위험)"
                    warn={overwrite} />
          <CheckRow checked={clearFirst} onChange={(v) => { setClearFirst(v); if (v) setOverwrite(true) }}
                    label="🗑 시작 전 모두 삭제"
                    sub="기존 모든 배정 DELETE 후 새로 채움 (가장 위험, manual_lock 보존)"
                    warn={clearFirst} danger={clearFirst} />
          <div style={{ height: 1, background: COLORS.borderFaint, margin: '4px 0' }} />
          {/* PR-2QQ-d-3 새 옵션 */}
          <CheckRow checked={usePriority} onChange={setUsePriority}
                    label="🎯 우선순위 + 균등 분배"
                    sub="P1/P2/P3 + 비선호 요일 + cycle 패턴 + 금/일 균등" />
          <CheckRow checked={enforceMinCoverage} onChange={setEnforceMinCoverage}
                    label="⚖️ 그룹 최소 인원 적용"
                    sub="cs_group_min_coverage 의 요일별 최소 인원 충족" />
        </div>

        {/* 결과 요약 */}
        {summary && (
          <div style={{
            ...GLASS.L3,
            background: applied ? COLORS.bgGreen : COLORS.bgBlue,
            border: `1px solid ${applied ? COLORS.borderGreen : COLORS.borderBlue}`,
            borderRadius: 12, padding: 14,
          }}>
            <div style={{
              fontSize: 13, fontWeight: 800, marginBottom: 10,
              color: applied ? COLORS.success : COLORS.info,
            }}>
              {applied ? '✅ 적용 완료' : '🔍 미리보기 (실제 변경 없음)'}
            </div>
            <div style={{
              display: 'grid', gridTemplateColumns: 'repeat(3, 1fr)', gap: 8,
              marginBottom: 10,
            }}>
              <Tile label="신규" value={summary.to_insert} tone="success" />
              <Tile label="갱신" value={summary.to_update} tone="info" />
              <Tile label="건너뜀" value={summary.skip_existing + summary.skip_holiday + summary.skip_no_member} tone="neutral" />
            </div>
            <div style={{ fontSize: 11, color: COLORS.textMuted, marginBottom: 6 }}>
              · 휴일 제외: {summary.skip_holiday} 셀
              · 연차 표시: {summary.leaves_marked}건
              · 기존 보존: {summary.skip_existing} 셀
              · 멤버 없음 그룹: {summary.skip_no_member} 셀
            </div>
            {Object.keys(summary.by_group).length > 0 && (
              <div style={{ marginTop: 10, paddingTop: 8, borderTop: `1px solid ${COLORS.borderFaint}` }}>
                <div style={{ fontSize: 11, fontWeight: 700, color: COLORS.textSecondary, marginBottom: 6 }}>
                  🚧 그룹별 결과
                </div>
                <div style={{ display: 'flex', flexDirection: 'column', gap: 3 }}>
                  {Object.entries(summary.by_group).map(([gid, s]) => (
                    <div key={gid} style={{
                      display: 'flex', alignItems: 'center', gap: 8,
                      padding: '4px 8px', borderRadius: 6,
                      background: s.generated > 0 ? COLORS.bgGreen : 'rgba(0,0,0,0.03)',
                      border: `1px solid ${s.generated > 0 ? COLORS.borderGreen : COLORS.borderFaint}`,
                      fontSize: 11,
                    }}>
                      <span style={{ flex: 1, fontWeight: 700, color: COLORS.textPrimary }}>
                        {gn(gid)}
                      </span>
                      <span style={{ color: COLORS.success, fontWeight: 800 }}>+ {s.generated}</span>
                      {s.skipped > 0 && (
                        <span style={{ color: COLORS.textMuted }}>· skip {s.skipped}</span>
                      )}
                    </div>
                  ))}
                </div>
              </div>
            )}

            {/* N-1 — 워커별 예상 근무 분포 (균형 막대) */}
            {workerCounts.size > 0 && maxCount > 0 && (
              <div style={{ marginTop: 10, paddingTop: 8, borderTop: `1px solid ${COLORS.borderFaint}` }}>
                <div style={{ fontSize: 11, fontWeight: 700, color: COLORS.textSecondary, marginBottom: 6 }}>
                  📊 워커별 예상 근무 분포 (이번 미리보기 기준)
                </div>
                <div style={{ display: 'flex', flexDirection: 'column', gap: 3, maxHeight: 180, overflowY: 'auto' }}>
                  {Array.from(workerCounts.entries())
                    .sort((a, b) => b[1] - a[1])
                    .map(([wId, count]) => {
                      const tone = wt(wId)
                      const pct = (count / maxCount) * 100
                      return (
                        <div key={wId} style={{
                          display: 'flex', alignItems: 'center', gap: 8, fontSize: 11,
                        }}>
                          <span style={{
                            minWidth: 70, fontWeight: 700, padding: '2px 6px', borderRadius: 4,
                            background: TONE_BG[tone] !== 'transparent' ? TONE_BG[tone] : undefined,
                            color: TONE_TEXT[tone] || COLORS.textPrimary,
                            textAlign: 'center', whiteSpace: 'nowrap',
                          }}>
                            {wn(wId)}
                          </span>
                          <div style={{
                            flex: 1, height: 14, background: 'rgba(0,0,0,0.04)',
                            borderRadius: 4, overflow: 'hidden', position: 'relative',
                          }}>
                            <div style={{
                              width: `${pct}%`, height: '100%',
                              background: COLORS.info, borderRadius: 4,
                              transition: 'width 0.3s',
                            }} />
                          </div>
                          <span style={{ minWidth: 28, fontWeight: 800, color: COLORS.textPrimary, textAlign: 'right' }}>
                            {count}
                          </span>
                        </div>
                      )
                    })}
                </div>
                <div style={{ fontSize: 9, color: COLORS.textMuted, marginTop: 4 }}>
                  ※ 미리보기 plan 의 처음 50건 기준 — 실제 적용 시 더 많을 수 있음
                </div>
              </div>
            )}
            {/* PR-2QQ-d-3 → PR-2SS-b — 경고 다중 타입 */}
            {summary.warning_count != null && summary.warning_count > 0 && (
              <div style={{
                marginTop: 10, padding: '8px 10px', borderRadius: 6,
                background: COLORS.bgRed, border: `1px solid ${COLORS.borderRed}`,
              }}>
                <div style={{ fontSize: 11, fontWeight: 800, color: COLORS.danger, marginBottom: 4 }}>
                  ⚠ 자동 생성 경고 ({summary.warning_count}건)
                </div>
                {summary.warn_by_type && (
                  <div style={{ display: 'flex', gap: 6, flexWrap: 'wrap', marginBottom: 6 }}>
                    {summary.warn_by_type.missing > 0 && (
                      <span style={pillStyle('warning')}>
                        🪫 인원 부족 {summary.warn_by_type.missing}건
                      </span>
                    )}
                    {summary.warn_by_type.next_day_block > 0 && (
                      <span style={pillStyle('danger')}>
                        🌙 익일 휴식 위반 {summary.warn_by_type.next_day_block}건
                      </span>
                    )}
                    {summary.warn_by_type.time_conflict > 0 && (
                      <span style={pillStyle('danger')}>
                        ⏱ 시간 겹침 {summary.warn_by_type.time_conflict}건
                      </span>
                    )}
                    {(summary.warn_by_type.consec_limit ?? 0) > 0 && (
                      <span style={pillStyle('warning')}>
                        📅 연속 한도 {summary.warn_by_type.consec_limit}건
                      </span>
                    )}
                    {(summary.warn_by_type.slot_blocked ?? 0) > 0 && (
                      <span style={pillStyle('neutral')}>
                        🚫 슬롯 거부 {summary.warn_by_type.slot_blocked}건
                      </span>
                    )}
                    {(summary.warn_by_type.group_skip ?? 0) > 0 && (
                      <span style={pillStyle('warning')}>
                        🛌 그룹 회피 {summary.warn_by_type.group_skip}건
                      </span>
                    )}
                  </div>
                )}
                <div style={{ fontSize: 11, color: COLORS.textSecondary, maxHeight: 140, overflowY: 'auto' }}>
                  {summary.warnings?.slice(0, 16).map((w, i) => {
                    if (w.type === 'missing') {
                      return <div key={i}>🪫 <strong>{w.group_name}</strong> · {w.date}: <span style={{ color: COLORS.danger }}>{w.missing}명 부족</span></div>
                    }
                    if (w.type === 'next_day_block') {
                      return (
                        <div key={i}>
                          🌙 {w.date}: <strong>{wn(w.worker_id)}</strong> 직전 {w.prev_end_date} 종료 후 {w.blocking_hours}h 미충족 → 후보 제외
                        </div>
                      )
                    }
                    if (w.type === 'time_conflict') {
                      return (
                        <div key={i}>
                          ⏱ {w.date}: <strong>{wn(w.worker_id)}</strong> 시간 겹침 ({sn(w.slot_a)} × {sn(w.slot_b)})
                        </div>
                      )
                    }
                    if (w.type === 'consec_limit') {
                      return (
                        <div key={i}>
                          📅 {w.date}: <strong>{wn(w.worker_id)}</strong> 연속 {w.limit}일 한도 → 후보 제외 ({sn(w.slot_id)})
                        </div>
                      )
                    }
                    if (w.type === 'slot_blocked') {
                      return (
                        <div key={i}>
                          🚫 {w.date}: <strong>{wn(w.worker_id)}</strong> 슬롯 거부 ({sn(w.slot_id)})
                        </div>
                      )
                    }
                    if (w.type === 'group_skip') {
                      return (
                        <div key={i}>
                          🛌 {w.date}: <strong>{wn(w.worker_id)}</strong> 그룹 회피일{w.reason ? ` — ${w.reason}` : ''}
                        </div>
                      )
                    }
                    return null
                  })}
                  {summary.warning_count > 16 && (
                    <div style={{ color: COLORS.textMuted, marginTop: 2 }}>
                      ... 외 {summary.warning_count - 16}건
                    </div>
                  )}
                </div>

                {/* N-28-a — 워커별 사유 통계 (어떤 워커가 어떤 사유로 자주 빠지는지) */}
                {(() => {
                  if (!summary.warnings || summary.warnings.length === 0) return null
                  const byWorker = new Map<string, { name: string;
                    next_day_block: number; time_conflict: number; consec_limit: number;
                    slot_blocked: number; group_skip: number; total: number }>()
                  for (const w of summary.warnings) {
                    if (!('worker_id' in w) || !w.worker_id) continue
                    const cur = byWorker.get(w.worker_id) || {
                      name: wn(w.worker_id),
                      next_day_block: 0, time_conflict: 0, consec_limit: 0,
                      slot_blocked: 0, group_skip: 0, total: 0,
                    }
                    if (w.type in cur) (cur as any)[w.type]++
                    cur.total++
                    byWorker.set(w.worker_id, cur)
                  }
                  const sorted = Array.from(byWorker.values()).sort((a, b) => b.total - a.total)
                  if (sorted.length === 0) return null
                  return (
                    <div style={{
                      marginTop: 8, padding: '6px 8px', borderRadius: 6,
                      background: '#fff', border: `1px solid ${COLORS.borderFaint}`,
                    }}>
                      <div style={{ fontSize: 10, fontWeight: 800, color: COLORS.textSecondary, marginBottom: 4 }}>
                        🧑 워커별 제외 사유 (TOP {Math.min(sorted.length, 10)})
                      </div>
                      <div style={{ display: 'flex', flexDirection: 'column', gap: 2, maxHeight: 160, overflowY: 'auto' }}>
                        {sorted.slice(0, 10).map(s => (
                          <div key={s.name} style={{
                            display: 'flex', alignItems: 'center', gap: 6,
                            fontSize: 11, padding: '2px 4px',
                          }}>
                            <span style={{ fontWeight: 700, color: COLORS.textPrimary, minWidth: 64 }}>
                              {s.name}
                            </span>
                            <span style={{
                              fontSize: 10, fontWeight: 700, color: COLORS.danger,
                              background: COLORS.bgRed, padding: '1px 6px', borderRadius: 4,
                            }}>{s.total}건</span>
                            <span style={{ fontSize: 10, color: COLORS.textMuted, flex: 1 }}>
                              {s.next_day_block > 0 && <span style={{ marginLeft: 6 }}>🌙 {s.next_day_block}</span>}
                              {s.time_conflict > 0 && <span style={{ marginLeft: 6 }}>⏱ {s.time_conflict}</span>}
                              {s.consec_limit > 0 && <span style={{ marginLeft: 6 }}>📅 {s.consec_limit}</span>}
                              {s.slot_blocked > 0 && <span style={{ marginLeft: 6 }}>🚫 {s.slot_blocked}</span>}
                              {s.group_skip > 0 && <span style={{ marginLeft: 6 }}>🛌 {s.group_skip}</span>}
                            </span>
                          </div>
                        ))}
                      </div>
                      <div style={{ marginTop: 4, fontSize: 10, color: COLORS.textMuted }}>
                        💡 한 워커가 자주 제외되면 → 시간(시프트) 「익일 휴식」 시간 / 워커 「연속 한도」 / 「월 최대 일수」 설정 검토
                      </div>
                    </div>
                  )
                })()}
              </div>
            )}
          </div>
        )}

        {error && (
          <div style={{
            padding: '8px 12px', borderRadius: 8,
            background: COLORS.bgRed, border: `1px solid ${COLORS.borderRed}`,
            color: COLORS.danger, fontSize: 13,
          }}>❌ {error}</div>
        )}

        {/* 액션 */}
        <div style={{ display: 'flex', justifyContent: 'space-between', gap: 8, marginTop: 4 }}>
          <button type="button" onClick={close} disabled={busy} style={{
            ...BTN.md, background: 'transparent', color: COLORS.textSecondary,
            border: `1px solid ${COLORS.borderFaint}`, cursor: 'pointer',
          }}>
            {applied ? '닫기' : '취소'}
          </button>
          <div style={{ display: 'flex', gap: 8 }}>
            <button type="button" onClick={() => run('preview')} disabled={busy} style={{
              ...BTN.sm, background: 'transparent', color: COLORS.info,
              border: `1px solid ${COLORS.borderBlue}`, cursor: busy ? 'not-allowed' : 'pointer',
            }}>
              {busy ? '계산 중...' : '🔄 다시 계산'}
            </button>
            {(() => {
              // summary 가 0건이면 비활성 (생성 의미 없음). 그 외는 활성
              const noChange = summary && (summary.to_insert + summary.to_update === 0)
              const dis = busy || applied || !!noChange
              return (
                <button type="button"
                        onClick={() => run('apply')}
                        disabled={dis}
                        style={{
                          ...BTN.lg,
                          background: clearFirst ? COLORS.danger : COLORS.success,
                          color: '#fff', border: 'none',
                          cursor: dis ? 'not-allowed' : 'pointer',
                          opacity: dis ? 0.5 : 1,
                        }}
                        title={noChange ? '변경 사항 없음' : ''}>
                  {applied ? '✅ 적용 완료'
                    : busy ? '진행 중...'
                    : clearFirst ? '🗑 초기화 + 적용'
                    : !summary ? '✨ 적용'
                    : `✨ ${summary.to_insert + summary.to_update}건 적용`}
                </button>
              )
            })()}
          </div>
        </div>
        {busy && !summary && (
          <div style={{
            fontSize: 11, color: COLORS.textMuted, textAlign: 'center', marginTop: -4,
          }}>
            ⏳ 자동 미리보기 중...
          </div>
        )}
        {!busy && !summary && !error && !applied && (
          <div style={{
            fontSize: 11, color: COLORS.textMuted, textAlign: 'center', marginTop: -4,
          }}>
            💡 옵션 변경 시 자동으로 다시 계산됩니다.
          </div>
        )}
      </div>
    </div>
  )
}

function CheckRow({ checked, onChange, label, sub, warn, danger }: {
  checked: boolean; onChange: (v: boolean) => void
  label: string; sub: string; warn?: boolean; danger?: boolean
}) {
  return (
    <label style={{
      display: 'flex', alignItems: 'flex-start', gap: 8,
      padding: '6px 8px', borderRadius: 6, cursor: 'pointer',
      background: warn ? (danger ? COLORS.bgRed : COLORS.bgAmber) : 'transparent',
    }}>
      <input type="checkbox" checked={checked}
             onChange={(e) => onChange(e.target.checked)}
             style={{ marginTop: 2 }} />
      <div style={{ flex: 1 }}>
        <div style={{
          fontSize: 13, fontWeight: 700,
          color: danger ? COLORS.danger : warn ? COLORS.warning : COLORS.textPrimary,
        }}>
          {label}
        </div>
        <div style={{ fontSize: 11, color: COLORS.textMuted, marginTop: 2 }}>{sub}</div>
      </div>
    </label>
  )
}

function Tile({ label, value, tone }: {
  label: string; value: number; tone: 'success' | 'info' | 'neutral'
}) {
  const tintMap = {
    success: { bg: COLORS.bgGreen, color: COLORS.success },
    info:    { bg: COLORS.bgBlue,  color: COLORS.info },
    neutral: { bg: COLORS.bgGray,  color: COLORS.textSecondary },
  }[tone]
  return (
    <div style={{
      background: tintMap.bg, borderRadius: 8, padding: '10px 12px', textAlign: 'center',
    }}>
      <div style={{ fontSize: 11, color: COLORS.textSecondary, fontWeight: 600 }}>{label}</div>
      <div style={{ fontSize: 22, fontWeight: 800, color: tintMap.color, lineHeight: 1.1 }}>{value}</div>
    </div>
  )
}
