'use client'
// ═══════════════════════════════════════════════════════════════════
// ComposeMode — 워커 기준 작성 모드 (PR-2H)
// 매트릭스 대신: 워커 1명 → 시프트 선택 → 31일 캘린더에 근무일 토글
// 빠른 입력: 평일/주말/요일별/범위 매크로
// ═══════════════════════════════════════════════════════════════════
import { useMemo, useState, useCallback } from 'react'
import { COLORS, GLASS, BTN, pillStyle } from '@/app/utils/ui-tokens'
import { TONE_BG, TONE_BORDER, TONE_TEXT } from '../utils/palette'
import { monthDays, dowIndex, DOW_LABEL } from '../utils/hours'
import { SPECIAL_LABEL } from '../utils/types'
import { getAuthHeader } from '@/app/utils/auth-client'
import AutoGenerateDialog from './AutoGenerateDialog'
import type {
  ScheduleDetail, Worker, ShiftSlot, Assignment, SpecialCode,
} from '../utils/types'

interface Props {
  detail: ScheduleDetail
  onChanged: () => void
}

const SPECIAL_OPTIONS: { value: SpecialCode; label: string; tone: 'info' | 'warning' | 'neutral' }[] = [
  { value: 'none',    label: '일반',    tone: 'info' },
  { value: 'am_half', label: '오전반차', tone: 'warning' },
  { value: 'pm_half', label: '오후반차', tone: 'warning' },
  { value: 'am_free', label: '오전F',   tone: 'info' },
  { value: 'pm_free', label: '오후F',   tone: 'info' },
  { value: 'off',     label: '휴무',    tone: 'neutral' },
]

export default function ComposeMode({ detail, onChanged }: Props) {
  const { schedule, slots, workers, assignments } = detail
  const days = useMemo(
    () => monthDays(schedule.year, schedule.month),
    [schedule.year, schedule.month],
  )

  const [selectedWorkerId, setSelectedWorkerId] = useState<string | null>(workers[0]?.id || null)
  const [selectedSlotId, setSelectedSlotId] = useState<string | null>(null)
  const [defaultSpecial, setDefaultSpecial] = useState<SpecialCode>('none')
  const [busy, setBusy] = useState(false)
  const [bulkText, setBulkText] = useState('')
  const [error, setError] = useState<string | null>(null)
  const [autoGenOpen, setAutoGenOpen] = useState(false)

  const selectedWorker = useMemo(
    () => workers.find(w => w.id === selectedWorkerId) || null,
    [workers, selectedWorkerId],
  )

  // 본인 배정 (모든 슬롯)
  const myAssignments = useMemo(
    () => assignments.filter(a => a.worker_id === selectedWorkerId),
    [assignments, selectedWorkerId],
  )

  // 본인이 가장 많이 쓰는 슬롯 (자동 선택)
  const recommendedSlotId = useMemo(() => {
    if (myAssignments.length === 0) return null
    const counter = new Map<string, number>()
    for (const a of myAssignments) {
      if (a.special_code === 'off') continue
      counter.set(a.shift_slot_id, (counter.get(a.shift_slot_id) || 0) + 1)
    }
    let max = 0; let pick: string | null = null
    for (const [k, v] of counter) { if (v > max) { max = v; pick = k } }
    return pick
  }, [myAssignments])

  const effectiveSlotId = selectedSlotId || recommendedSlotId || (slots[0]?.id || null)
  const effectiveSlot = slots.find(s => s.id === effectiveSlotId) || null

  // (date) → 본인이 effective 슬롯에 배정된 assignment
  const cellByDate = useMemo(() => {
    const m = new Map<string, Assignment>()
    if (!effectiveSlotId) return m
    for (const a of myAssignments) {
      if (a.shift_slot_id === effectiveSlotId) m.set(a.work_date, a)
    }
    return m
  }, [myAssignments, effectiveSlotId])

  // 다른 워커가 같은 (date, slot) 점유 중인 셀 — 충돌 표시
  const conflictByDate = useMemo(() => {
    const m = new Map<string, Worker | null>()
    if (!effectiveSlotId) return m
    for (const a of assignments) {
      if (a.shift_slot_id !== effectiveSlotId) continue
      if (a.worker_id && a.worker_id !== selectedWorkerId) {
        m.set(a.work_date, workers.find(w => w.id === a.worker_id) || null)
      }
    }
    return m
  }, [assignments, effectiveSlotId, selectedWorkerId, workers])

  // ── 단일 셀 토글 ────────────────────────────────────────────────
  const toggleCell = useCallback(async (isoDate: string) => {
    if (!selectedWorkerId || !effectiveSlotId) return
    const existing = cellByDate.get(isoDate)
    setBusy(true); setError(null)
    try {
      const auth = await getAuthHeader()
      if (existing) {
        // 본인 배정 → 삭제
        const res = await fetch(`/api/call-scheduler/assignments?id=${existing.id}`, {
          method: 'DELETE', headers: auth,
        })
        const json = await res.json()
        if (!res.ok) throw new Error(json?.error || '삭제 실패')
      } else {
        // 신규 배정
        const res = await fetch('/api/call-scheduler/assignments', {
          method: 'PUT',
          headers: { 'Content-Type': 'application/json', ...auth },
          body: JSON.stringify({
            schedule_id: schedule.id,
            work_date: isoDate,
            shift_slot_id: effectiveSlotId,
            worker_id: selectedWorkerId,
            special_code: defaultSpecial,
          }),
        })
        const json = await res.json()
        if (!res.ok) throw new Error(json?.error || '저장 실패')
      }
      onChanged()
    } catch (e: any) { setError(e?.message || '오류') }
    finally { setBusy(false) }
  }, [selectedWorkerId, effectiveSlotId, cellByDate, schedule.id, defaultSpecial, onChanged])

  // ── 일괄 적용 ───────────────────────────────────────────────────
  const applyBulk = useCallback(async (targetDates: string[], opts?: { mode?: 'add' | 'remove' | 'toggle' }) => {
    if (!selectedWorkerId || !effectiveSlotId || targetDates.length === 0) return
    const mode = opts?.mode || 'toggle'
    setBusy(true); setError(null)
    try {
      const auth = await getAuthHeader()
      for (const d of targetDates) {
        const existing = cellByDate.get(d)
        const conflict = conflictByDate.get(d)
        // remove 모드: 본인 배정만 삭제, 충돌은 무시
        if (mode === 'remove') {
          if (existing) {
            await fetch(`/api/call-scheduler/assignments?id=${existing.id}`, {
              method: 'DELETE', headers: auth,
            })
          }
          continue
        }
        // add 모드: 충돌 셀은 덮어쓰기 (worker_id 변경)
        if (mode === 'add') {
          if (existing) continue  // 이미 본인 → 무시
          await fetch('/api/call-scheduler/assignments', {
            method: 'PUT',
            headers: { 'Content-Type': 'application/json', ...auth },
            body: JSON.stringify({
              schedule_id: schedule.id, work_date: d,
              shift_slot_id: effectiveSlotId,
              worker_id: selectedWorkerId, special_code: defaultSpecial,
            }),
          })
          continue
        }
        // toggle (디폴트): 본인 있으면 삭제, 없으면 추가
        if (existing) {
          await fetch(`/api/call-scheduler/assignments?id=${existing.id}`, {
            method: 'DELETE', headers: auth,
          })
        } else {
          await fetch('/api/call-scheduler/assignments', {
            method: 'PUT',
            headers: { 'Content-Type': 'application/json', ...auth },
            body: JSON.stringify({
              schedule_id: schedule.id, work_date: d,
              shift_slot_id: effectiveSlotId,
              worker_id: selectedWorkerId, special_code: defaultSpecial,
            }),
          })
        }
      }
      onChanged()
    } catch (e: any) { setError(e?.message || '오류') }
    finally { setBusy(false) }
  }, [selectedWorkerId, effectiveSlotId, cellByDate, conflictByDate, schedule.id, defaultSpecial, onChanged])

  // ── 매크로 ─────────────────────────────────────────────────────
  const weekdayDates = days.filter(d => { const w = dowIndex(d); return w >= 1 && w <= 5 })
  const weekendDates = days.filter(d => { const w = dowIndex(d); return w === 0 || w === 6 })
  const dowDates = (dow: number) => days.filter(d => dowIndex(d) === dow)

  // ── 한 줄 입력 파서 — "1, 4, 6, 7-12, 15" → ['2026-05-01', ...] ──
  const parseBulkText = (txt: string): string[] => {
    const result = new Set<number>()
    for (const token of txt.split(/[,\s]+/)) {
      const t = token.trim()
      if (!t) continue
      const range = t.match(/^(\d+)\s*-\s*(\d+)$/)
      if (range) {
        const a = Number(range[1]); const b = Number(range[2])
        for (let i = Math.min(a, b); i <= Math.max(a, b); i++) result.add(i)
      } else if (/^\d+$/.test(t)) {
        result.add(Number(t))
      }
    }
    const lastDay = new Date(schedule.year, schedule.month, 0).getDate()
    return Array.from(result)
      .filter(d => d >= 1 && d <= lastDay)
      .map(d => `${schedule.year}-${String(schedule.month).padStart(2, '0')}-${String(d).padStart(2, '0')}`)
  }

  return (
    <div>
      {/* 자동 생성 배너 */}
      <div style={{
        ...GLASS.L3,
        background: COLORS.bgViolet,
        border: `1px solid ${COLORS.borderViolet}`,
        borderRadius: 12, padding: '10px 14px', marginBottom: 12,
        display: 'flex', alignItems: 'center', justifyContent: 'space-between',
        flexWrap: 'wrap', gap: 8,
      }}>
        <div>
          <div style={{ fontSize: 13, fontWeight: 800, color: '#7c3aed' }}>
            ✨ 그룹 셋팅 기반 자동 생성
          </div>
          <div style={{ fontSize: 11, color: COLORS.textMuted, marginTop: 2 }}>
            설정한 시프트 그룹·휴일·연차를 활용해 한 달을 한 번에 채웁니다. 수동 조정은 그 후에.
          </div>
        </div>
        <button type="button" onClick={() => setAutoGenOpen(true)}
                style={{
                  ...BTN.md, background: '#7c3aed', color: '#fff', border: 'none',
                  cursor: 'pointer', whiteSpace: 'nowrap',
                }}>
          ✨ 자동 생성
        </button>
      </div>

      <div style={{
        display: 'grid', gridTemplateColumns: '240px 1fr', gap: 12,
        alignItems: 'start',
      }}>
      {/* 좌측 — 워커 리스트 + 부담 인디케이터 (PR-2T) */}
      {(() => {
        // 워커별 통계 한 번에 계산
        const allStats = workers.map(w => {
          const mine = assignments.filter(a => a.worker_id === w.id && a.special_code !== 'off')
          return {
            wId: w.id,
            count: mine.length,
            hours: mine.reduce((s, a) => s + Number(a.computed_hours || 0), 0),
          }
        })
        const activeWorkers = allStats.filter(s => s.hours > 0)
        const avgHours = activeWorkers.length > 0
          ? activeWorkers.reduce((s, x) => s + x.hours, 0) / activeWorkers.length
          : 0
        const maxHours = Math.max(1, ...allStats.map(x => x.hours))

        return (
          <div style={{
            ...GLASS.L4, borderRadius: 12, padding: 8,
            maxHeight: 'calc(100vh - 200px)', overflowY: 'auto',
            position: 'sticky', top: 12,
          }}>
            <div style={{
              padding: '6px 8px', fontSize: 12, fontWeight: 800,
              color: COLORS.textPrimary,
              display: 'flex', alignItems: 'baseline', justifyContent: 'space-between',
            }}>
              <span>근무자 ({workers.length})</span>
              {avgHours > 0 && (
                <span style={{ fontSize: 10, fontWeight: 500, color: COLORS.textMuted }}>
                  평균 {Math.round(avgHours)}h
                </span>
              )}
            </div>

            {workers.map(w => {
              const stats = allStats.find(x => x.wId === w.id)!
              const active = w.id === selectedWorkerId
              const ratio = maxHours > 0 ? stats.hours / maxHours : 0
              const dev = avgHours > 0 ? (stats.hours - avgHours) / avgHours : 0
              // 균형 색상: ±20% 이내 = 녹색, +20% 초과 = 빨강(과로), -20% 미만 = 노랑(부족)
              const tone: 'ok' | 'over' | 'under' | 'empty' =
                stats.hours === 0 ? 'empty'
                : Math.abs(dev) <= 0.2 ? 'ok'
                : dev > 0 ? 'over'
                : 'under'
              const barColor = tone === 'over' ? COLORS.danger
                : tone === 'under' ? COLORS.warning
                : tone === 'ok' ? COLORS.success
                : COLORS.borderFaint

              return (
                <button
                  key={w.id}
                  type="button"
                  onClick={() => { setSelectedWorkerId(w.id); setSelectedSlotId(null) }}
                  style={{
                    width: '100%', padding: '6px 8px', borderRadius: 6,
                    background: active ? TONE_BG[w.color_tone] : 'transparent',
                    border: `1px solid ${active ? COLORS.borderBlue : 'transparent'}`,
                    cursor: 'pointer', textAlign: 'left',
                    display: 'flex', flexDirection: 'column', gap: 3,
                    marginBottom: 2,
                  }}
                  title={
                    avgHours > 0
                      ? `${w.name} — ${Math.round(stats.hours)}h (평균 ${Math.round(avgHours)}h ${dev >= 0 ? '+' : ''}${Math.round(dev * 100)}%)`
                      : `${w.name}`
                  }
                >
                  <div style={{
                    display: 'flex', justifyContent: 'space-between', alignItems: 'center',
                  }}>
                    <div style={{ display: 'flex', alignItems: 'center', gap: 6, minWidth: 0 }}>
                      <span style={{
                        fontWeight: 700, color: TONE_TEXT[w.color_tone], fontSize: 13,
                        whiteSpace: 'nowrap', overflow: 'hidden', textOverflow: 'ellipsis',
                      }}>
                        {w.name}
                      </span>
                      {w.group_label && (
                        <span style={{ fontSize: 9, color: COLORS.textMuted, whiteSpace: 'nowrap' }}>
                          {w.group_label}
                        </span>
                      )}
                    </div>
                    <span style={{
                      fontSize: 10, fontWeight: 700,
                      color: tone === 'over' ? COLORS.danger
                        : tone === 'under' ? COLORS.warning
                        : COLORS.textMuted,
                      whiteSpace: 'nowrap',
                    }}>
                      {stats.count}일 / {Math.round(stats.hours)}h
                    </span>
                  </div>

                  {/* 부담 막대 */}
                  <div style={{
                    height: 4, borderRadius: 2,
                    background: 'rgba(0,0,0,0.05)',
                    overflow: 'hidden', position: 'relative',
                  }}>
                    <div style={{
                      width: `${ratio * 100}%`, height: '100%',
                      background: barColor,
                      transition: 'width 0.2s',
                    }} />
                    {/* 평균 표시 (avgHours/maxHours 위치에 흰 마커) */}
                    {avgHours > 0 && maxHours > 0 && (
                      <div style={{
                        position: 'absolute', top: -1, bottom: -1,
                        left: `${(avgHours / maxHours) * 100}%`,
                        width: 1, background: 'rgba(0,0,0,0.4)',
                      }} title={`평균 ${Math.round(avgHours)}h`} />
                    )}
                  </div>

                  {/* 편차 라벨 (±20% 벗어났을 때만) */}
                  {tone !== 'empty' && tone !== 'ok' && (
                    <div style={{
                      fontSize: 9, fontWeight: 700,
                      color: tone === 'over' ? COLORS.danger : COLORS.warning,
                      textAlign: 'right', lineHeight: 1,
                    }}>
                      {tone === 'over' ? '⚠ 과로' : '⬇ 부족'}
                      {' '}{dev >= 0 ? '+' : ''}{Math.round(dev * 100)}%
                    </div>
                  )}
                </button>
              )
            })}
          </div>
        )
      })()}

      {/* 우측 — 작성 패널 */}
      <div style={{ ...GLASS.L4, borderRadius: 12, padding: 16 }}>
        {!selectedWorker ? (
          <div style={{ padding: 60, textAlign: 'center', color: COLORS.textMuted }}>
            좌측에서 근무자를 선택하세요.
          </div>
        ) : (
          <>
            {/* 워커 헤더 */}
            <div style={{
              display: 'flex', alignItems: 'center', justifyContent: 'space-between',
              marginBottom: 14, flexWrap: 'wrap', gap: 8,
            }}>
              <div style={{ display: 'flex', alignItems: 'center', gap: 12 }}>
                <h2 style={{
                  fontSize: 18, fontWeight: 800, margin: 0,
                  color: TONE_TEXT[selectedWorker.color_tone],
                  background: TONE_BG[selectedWorker.color_tone],
                  padding: '4px 12px', borderRadius: 6,
                }}>
                  {selectedWorker.name}
                </h2>
                <span style={{ fontSize: 12, color: COLORS.textMuted }}>
                  {myAssignments.filter(a => a.special_code !== 'off').length}일 근무
                  {' · '}
                  {Math.round(myAssignments.reduce((s, a) => s + Number(a.computed_hours || 0), 0) * 10) / 10}h
                </span>
              </div>
            </div>

            {/* 시프트 선택 */}
            <div style={{ marginBottom: 12 }}>
              <div style={{ fontSize: 12, fontWeight: 700, color: COLORS.textSecondary, marginBottom: 6 }}>
                근무 시프트 (시간대)
                {recommendedSlotId === effectiveSlotId && !selectedSlotId && (
                  <span style={{ marginLeft: 6, fontSize: 10, color: COLORS.info }}>
                    💡 본인 최다 근무 시프트 자동 선택
                  </span>
                )}
              </div>
              <div style={{ display: 'flex', flexWrap: 'wrap', gap: 4 }}>
                {slots.map(s => (
                  <button
                    key={s.id}
                    type="button"
                    onClick={() => setSelectedSlotId(s.id)}
                    style={{
                      padding: '4px 10px', borderRadius: 6, fontSize: 11, fontWeight: 600,
                      background: effectiveSlotId === s.id ? COLORS.bgBlue : 'transparent',
                      color: effectiveSlotId === s.id ? COLORS.info : COLORS.textSecondary,
                      border: `1px solid ${effectiveSlotId === s.id ? COLORS.borderBlue : COLORS.borderFaint}`,
                      cursor: 'pointer', whiteSpace: 'nowrap',
                    }}
                  >
                    <span style={{ color: COLORS.textMuted, marginRight: 4 }}>{s.code}</span>
                    {s.label}
                  </button>
                ))}
              </div>
            </div>

            {/* 특수코드 (근무 추가 시 default) */}
            <div style={{ marginBottom: 12 }}>
              <div style={{ fontSize: 12, fontWeight: 700, color: COLORS.textSecondary, marginBottom: 6 }}>
                근무 추가 시 적용할 특수코드 (기본: 일반)
              </div>
              <div style={{ display: 'flex', flexWrap: 'wrap', gap: 4 }}>
                {SPECIAL_OPTIONS.map(opt => (
                  <button
                    key={opt.value}
                    type="button"
                    onClick={() => setDefaultSpecial(opt.value)}
                    style={{
                      padding: '3px 10px', borderRadius: 999, fontSize: 11, fontWeight: 700,
                      background: defaultSpecial === opt.value ? COLORS.bgBlue : 'transparent',
                      color: defaultSpecial === opt.value ? COLORS.info : COLORS.textSecondary,
                      border: `1px solid ${defaultSpecial === opt.value ? COLORS.borderBlue : COLORS.borderFaint}`,
                      cursor: 'pointer',
                    }}
                  >
                    {opt.label}
                  </button>
                ))}
              </div>
            </div>

            {/* 빠른 입력 매크로 */}
            <div style={{
              ...GLASS.L1, borderRadius: 8, padding: 10, marginBottom: 12,
              display: 'flex', flexDirection: 'column', gap: 8,
            }}>
              <div style={{ fontSize: 11, fontWeight: 700, color: COLORS.textSecondary }}>
                빠른 입력 — 일괄 추가 / 제거
              </div>
              <div style={{ display: 'flex', flexWrap: 'wrap', gap: 4 }}>
                <Macro label="평일 추가" onClick={() => applyBulk(weekdayDates, { mode: 'add' })} />
                <Macro label="평일 제거" onClick={() => applyBulk(weekdayDates, { mode: 'remove' })} tone="danger" />
                <Macro label="주말 추가" onClick={() => applyBulk(weekendDates, { mode: 'add' })} />
                <Macro label="주말 제거" onClick={() => applyBulk(weekendDates, { mode: 'remove' })} tone="danger" />
                <Macro label="전체 추가" onClick={() => applyBulk(days, { mode: 'add' })} />
                <Macro label="전체 제거" onClick={() => applyBulk(days, { mode: 'remove' })} tone="danger" />
              </div>
              <div style={{ display: 'flex', flexWrap: 'wrap', gap: 4 }}>
                {[1, 2, 3, 4, 5, 6, 0].map(dow => (
                  <Macro
                    key={dow}
                    label={`${DOW_LABEL[dow]}만 토글`}
                    onClick={() => applyBulk(dowDates(dow))}
                    tone="neutral"
                  />
                ))}
              </div>
              <div style={{ display: 'flex', gap: 6 }}>
                <input
                  type="text"
                  value={bulkText}
                  onChange={(e) => setBulkText(e.target.value)}
                  placeholder="예: 1, 4, 6, 7-15, 18, 21"
                  style={{
                    ...GLASS.L1, flex: 1, padding: '6px 10px', borderRadius: 6,
                    fontSize: 12, color: COLORS.textPrimary, outline: 'none',
                  }}
                />
                <button
                  type="button"
                  disabled={busy || !bulkText.trim()}
                  onClick={() => {
                    const dates = parseBulkText(bulkText)
                    if (dates.length === 0) { setError('파싱할 일자가 없습니다.'); return }
                    applyBulk(dates, { mode: 'add' })
                  }}
                  style={{
                    ...BTN.sm, background: COLORS.success, color: '#fff', border: 'none',
                    cursor: busy || !bulkText.trim() ? 'not-allowed' : 'pointer',
                  }}
                >
                  추가
                </button>
                <button
                  type="button"
                  disabled={busy || !bulkText.trim()}
                  onClick={() => {
                    const dates = parseBulkText(bulkText)
                    if (dates.length === 0) { setError('파싱할 일자가 없습니다.'); return }
                    applyBulk(dates, { mode: 'remove' })
                  }}
                  style={{
                    ...BTN.sm, background: 'transparent', color: COLORS.danger,
                    border: `1px solid ${COLORS.borderRed}`,
                    cursor: busy || !bulkText.trim() ? 'not-allowed' : 'pointer',
                  }}
                >
                  제거
                </button>
              </div>
            </div>

            {error && (
              <div style={{
                padding: '8px 12px', borderRadius: 6, marginBottom: 10,
                background: COLORS.bgRed, border: `1px solid ${COLORS.borderRed}`,
                color: COLORS.danger, fontSize: 12,
                display: 'flex', justifyContent: 'space-between', alignItems: 'center',
              }}>
                <span>❌ {error}</span>
                <button onClick={() => setError(null)} style={{
                  background: 'transparent', border: 'none', cursor: 'pointer',
                  color: COLORS.textMuted,
                }}>×</button>
              </div>
            )}

            {/* 31일 캘린더 그리드 */}
            <div>
              <div style={{
                display: 'flex', alignItems: 'center', justifyContent: 'space-between',
                marginBottom: 6,
              }}>
                <div style={{ fontSize: 12, fontWeight: 700, color: COLORS.textSecondary }}>
                  근무일 (클릭으로 토글 — 본인이 있는 셀: 진한 색, 다른 사람: 회색)
                </div>
                <div style={{ fontSize: 11, color: COLORS.textMuted }}>
                  {effectiveSlot && `시간: ${effectiveSlot.label}`}
                </div>
              </div>
              <div style={{
                display: 'grid', gridTemplateColumns: 'repeat(7, 1fr)', gap: 4,
                fontSize: 12,
              }}>
                {DOW_LABEL.map((dow, i) => (
                  <div key={dow} style={{
                    fontSize: 10, fontWeight: 700, textAlign: 'center', padding: '4px 0',
                    color: i === 0 ? COLORS.danger : i === 6 ? COLORS.info : COLORS.textMuted,
                  }}>
                    {dow}
                  </div>
                ))}
                {/* 첫 주 빈칸 */}
                {(() => {
                  if (days.length === 0) return null
                  const firstDow = dowIndex(days[0])
                  return Array.from({ length: firstDow }, (_, i) => (
                    <div key={`empty-${i}`} />
                  ))
                })()}
                {days.map(d => {
                  const dow = dowIndex(d)
                  const day = Number(d.split('-')[2])
                  const mine = cellByDate.get(d)
                  const conflict = conflictByDate.get(d)
                  const tone = selectedWorker.color_tone
                  const isMine = !!mine && mine.special_code !== 'off'
                  return (
                    <button
                      key={d}
                      type="button"
                      onClick={() => toggleCell(d)}
                      disabled={busy}
                      title={
                        isMine ? `${selectedWorker.name} 근무 (클릭: 제거)`
                        : conflict ? `다른 워커: ${conflict.name} (클릭: 덮어쓰기)`
                        : '클릭: 추가'
                      }
                      style={{
                        height: 48, padding: 4, borderRadius: 6,
                        background: isMine ? TONE_BG[tone]
                          : conflict ? COLORS.bgGray
                          : 'transparent',
                        border: `1px solid ${
                          isMine ? TONE_BORDER[tone]
                          : conflict ? COLORS.borderFaint
                          : COLORS.borderFaint
                        }`,
                        color: isMine ? TONE_TEXT[tone]
                          : conflict ? COLORS.textMuted
                          : COLORS.textPrimary,
                        cursor: busy ? 'not-allowed' : 'pointer',
                        display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center',
                        gap: 2, opacity: busy ? 0.6 : 1,
                      }}
                    >
                      <span style={{
                        fontSize: 13, fontWeight: 700,
                        color: dow === 0 ? COLORS.danger : dow === 6 ? COLORS.info : 'inherit',
                      }}>
                        {day}
                      </span>
                      {mine && mine.special_code !== 'none' && mine.special_code !== 'off' && (
                        <span style={{
                          ...pillStyle(mine.special_code.endsWith('_half') ? 'warning' : 'info'),
                          fontSize: 8, padding: '0 3px',
                        }}>
                          {mine.special_code === 'am_half' ? '오반' : mine.special_code === 'pm_half' ? '오후반' : 'F'}
                        </span>
                      )}
                      {!mine && conflict && (
                        <span style={{ fontSize: 9, color: COLORS.textMuted, lineHeight: 1 }}>
                          {conflict.name}
                        </span>
                      )}
                      {mine?.special_code === 'off' && (
                        <span style={{ fontSize: 9, color: COLORS.textMuted, lineHeight: 1 }}>휴무</span>
                      )}
                    </button>
                  )
                })}
              </div>
            </div>

            {/* 본인 시간표 요약 */}
            <div style={{
              marginTop: 12, paddingTop: 10,
              borderTop: `1px solid ${COLORS.borderFaint}`,
              fontSize: 11, color: COLORS.textMuted, display: 'flex', flexWrap: 'wrap', gap: 12,
            }}>
              <span>📅 근무 {myAssignments.filter(a => a.special_code !== 'off').length}일</span>
              <span>⏰ {Math.round(myAssignments.reduce((s, a) => s + Number(a.computed_hours || 0), 0) * 10) / 10}h</span>
              <span>🌙 야간 {myAssignments.filter(a => {
                const slot = slots.find(s => s.id === a.shift_slot_id)
                return slot?.is_overnight && a.special_code !== 'off'
              }).length}회</span>
              <span>⏸ 반차 {myAssignments.filter(a => a.special_code === 'am_half' || a.special_code === 'pm_half').length}회</span>
              <span>💤 휴무 {myAssignments.filter(a => a.special_code === 'off').length}회</span>
            </div>
          </>
        )}
      </div>
      </div>

      <AutoGenerateDialog
        open={autoGenOpen}
        onClose={() => setAutoGenOpen(false)}
        scheduleId={schedule.id}
        onCompleted={onChanged}
      />
    </div>
  )
}

function Macro({ label, onClick, tone = 'primary' }: {
  label: string
  onClick: () => void
  tone?: 'primary' | 'danger' | 'neutral'
}) {
  const styleMap = {
    primary: { bg: COLORS.bgBlue,  color: COLORS.info,    border: COLORS.borderBlue },
    danger:  { bg: 'transparent',  color: COLORS.danger,  border: COLORS.borderRed },
    neutral: { bg: 'transparent',  color: COLORS.textSecondary, border: COLORS.borderFaint },
  }[tone]
  return (
    <button
      type="button"
      onClick={onClick}
      style={{
        padding: '3px 8px', borderRadius: 6, fontSize: 11, fontWeight: 700,
        background: styleMap.bg, color: styleMap.color,
        border: `1px solid ${styleMap.border}`, cursor: 'pointer',
        whiteSpace: 'nowrap',
      }}
    >
      {label}
    </button>
  )
}
