#!/usr/bin/env node
/**
 * install-hook.js — git pre-commit hook 설치/제거.
 *
 * 사용:
 *   npm run harness:install-hook       (설치)
 *   npm run harness:install-hook -- --uninstall   (제거)
 *
 * Hook 동작:
 *   - 매 commit 직전에 harness-lint 실행
 *   - 새 critical 위반 0 일 때만 commit 통과
 *   - lint-violations.md 자동 append → 누적 분석
 *
 * (CLAUDE.md § 0-1 자동화 안전장치)
 */
const fs = require('fs')
const path = require('path')

const ROOT = path.resolve(__dirname, '../..')
const HOOK_PATH = path.join(ROOT, '.git/hooks/pre-commit')
const HOOK_MARKER = '# harness-lint-hook v1'

const HOOK_CONTENT = `#!/bin/sh
${HOOK_MARKER}
# Auto-generated by harness-engineering/scripts/install-hook.js
# 평가 → 훅 → 기록 → 개선 사이클 자동화

# .ts/.tsx/.sql/prisma 파일 변경된 경우만 lint 실행 (성능)
RELEVANT_FILES=$(git diff --cached --name-only --diff-filter=ACM | grep -E '\\.(ts|tsx|sql|prisma)$' || true)
if [ -z "$RELEVANT_FILES" ]; then
  exit 0
fi

echo ""
echo "▸ harness-lint pre-commit hook 실행..."
node harness-engineering/scripts/harness-lint.js
RESULT=$?

if [ $RESULT -ne 0 ]; then
  echo ""
  echo "❌ harness-lint 실패 — commit 차단"
  echo "   수정 후 재시도, 또는 의도된 변경이라면:"
  echo "     npm run lint:harness:baseline"
  echo ""
  echo "   강제 우회 (권장 X):"
  echo "     git commit --no-verify"
  exit 1
fi
exit 0
`

const args = new Set(process.argv.slice(2))

function uninstall() {
  if (!fs.existsSync(HOOK_PATH)) {
    console.log('[install-hook] hook 없음 — 제거할 것 없음')
    return
  }
  const content = fs.readFileSync(HOOK_PATH, 'utf-8')
  if (!content.includes(HOOK_MARKER)) {
    console.log('[install-hook] 다른 hook 이 설치됨 — 직접 제거 필요:', HOOK_PATH)
    return
  }
  fs.unlinkSync(HOOK_PATH)
  console.log('[install-hook] ✅ hook 제거 완료')
}

function install() {
  // .git 디렉토리 존재 확인
  const gitDir = path.join(ROOT, '.git')
  if (!fs.existsSync(gitDir)) {
    console.error('[install-hook] ❌ .git 디렉토리 없음 — git 저장소가 아님')
    process.exit(1)
  }

  // 기존 hook 백업
  if (fs.existsSync(HOOK_PATH)) {
    const existing = fs.readFileSync(HOOK_PATH, 'utf-8')
    if (existing.includes(HOOK_MARKER)) {
      console.log('[install-hook] 이미 설치됨 — 갱신')
    } else {
      const backup = HOOK_PATH + '.backup-' + Date.now()
      fs.copyFileSync(HOOK_PATH, backup)
      console.log(`[install-hook] 기존 hook 백업 → ${path.relative(ROOT, backup)}`)
    }
  }

  fs.writeFileSync(HOOK_PATH, HOOK_CONTENT)
  fs.chmodSync(HOOK_PATH, 0o755)
  console.log(`[install-hook] ✅ hook 설치 완료 → ${path.relative(ROOT, HOOK_PATH)}`)
  console.log('  매 commit 시 자동 실행: npm run lint:harness')
  console.log('  강제 우회: git commit --no-verify (권장 X)')
}

if (args.has('--uninstall')) uninstall()
else install()
