#!/usr/bin/env node
/**
 * install-hook.js — git pre-commit hook 설치/제거.
 *
 * 사용:
 *   npm run harness:install-hook       (설치)
 *   npm run harness:install-hook -- --uninstall   (제거)
 *
 * Hook 동작:
 *   - 매 commit 직전에 harness-lint 실행
 *   - 새 critical 위반 0 일 때만 commit 통과
 *   - lint-violations.md 자동 append → 누적 분석
 *
 * (CLAUDE.md § 0-1 자동화 안전장치)
 */
const fs = require('fs')
const path = require('path')
const { execSync } = require('child_process')

const ROOT = path.resolve(__dirname, '../..')
const HOOK_PATH = path.join(ROOT, '.git/hooks/pre-commit')
const HOOK_MARKER = '# harness-lint-hook v1'

// PR-COWORK (2026-05-09): hooksPath 자가 진단
//   다른 cowork 세션이 git config 오염 시 (예: hooksPath 가 다른 세션 경로) 자동 감지 + 수정
function checkHooksPath() {
  try {
    const out = execSync('git config --get core.hooksPath', { cwd: ROOT, encoding: 'utf-8' }).trim()
    if (!out) return { ok: true, hooksPath: null }
    // hooksPath 가 ROOT/.git/hooks 와 일치하는지 확인
    const expected = path.join(ROOT, '.git/hooks')
    const actual = path.resolve(ROOT, out)
    if (actual !== expected) {
      return { ok: false, hooksPath: out, expected, reason: 'mismatch' }
    }
    return { ok: true, hooksPath: out }
  } catch (e) {
    // git config --get 가 fail = hooksPath 미설정 (정상)
    return { ok: true, hooksPath: null }
  }
}

function fixHooksPath() {
  try {
    execSync('git config --unset core.hooksPath', { cwd: ROOT })
    console.log('[install-hook] ✅ core.hooksPath unset 완료 (기본 .git/hooks 사용)')
    return true
  } catch (e) {
    console.error('[install-hook] ❌ core.hooksPath unset 실패:', e.message)
    return false
  }
}
// PR-2SS-Z3 — pre-push hook (강력 차단 — pre-commit 우회 시에도 push 차단)
const PUSH_HOOK_PATH = path.join(ROOT, '.git/hooks/pre-push')
const PUSH_HOOK_MARKER = '# cowork-pre-push-hook v1'

const HOOK_CONTENT = `#!/bin/sh
${HOOK_MARKER}
# Auto-generated by harness-engineering/scripts/install-hook.js
# 평가 → 훅 → 기록 → 개선 사이클 자동화

# .ts/.tsx/.sql/prisma 파일 변경된 경우만 lint 실행 (성능)
RELEVANT_FILES=$(git diff --cached --name-only --diff-filter=ACM | grep -E '\\.(ts|tsx|sql|prisma)$' || true)
if [ -z "$RELEVANT_FILES" ]; then
  exit 0
fi

echo ""
echo "▸ harness-lint pre-commit hook 실행..."
node harness-engineering/scripts/harness-lint.js
RESULT=$?

if [ $RESULT -ne 0 ]; then
  echo ""
  echo "❌ harness-lint 실패 — commit 차단"
  echo "   수정 후 재시도, 또는 의도된 변경이라면:"
  echo "     npm run lint:harness:baseline"
  echo ""
  echo "   강제 우회 (권장 X):"
  echo "     git commit --no-verify"
  exit 1
fi
exit 0
`

// PR-2SS-Z3 — pre-push hook
// pre-commit 이 --no-verify 로 우회되어도 push 단계에서 또 차단.
// push 하려는 모든 새 commit 을 검사해서 multi-module 위반 발견 시 push 자체 차단.
const PUSH_HOOK_CONTENT = `#!/bin/sh
${PUSH_HOOK_MARKER}
# Auto-generated by harness-engineering/scripts/install-hook.js
# CLAUDE.md 규칙 21 — Cowork 멀티 세션 staging 침범 방지 (강력 차단)

# COWORK_ALLOW_MULTI_MODULE=1 면 우회 (의도적 cross-module push)
if [ "$COWORK_ALLOW_MULTI_MODULE" = "1" ]; then
  echo "⚠ COWORK_ALLOW_MULTI_MODULE=1 — multi-module push 허용"
  exit 0
fi

REMOTE_NAME="$1"
REMOTE_URL="$2"

# stdin 으로 push 대상 ref 들 받음
# 형식: <local_ref> <local_sha> <remote_ref> <remote_sha>
EXIT_CODE=0
while read local_ref local_sha remote_ref remote_sha; do
  # 삭제 push 는 skip
  if [ "$local_sha" = "0000000000000000000000000000000000000000" ]; then
    continue
  fi

  # 새 branch push 면 — 너무 많은 commit 검사 회피, 최근 20개만
  if [ "$remote_sha" = "0000000000000000000000000000000000000000" ]; then
    RANGE="$local_sha"
    LIMIT=20
  else
    RANGE="$remote_sha..$local_sha"
    LIMIT=200
  fi

  # 검사 대상 commit 목록 (최근부터)
  COMMITS=$(git rev-list --max-count=$LIMIT "$RANGE" 2>/dev/null)
  if [ -z "$COMMITS" ]; then
    continue
  fi

  for commit in $COMMITS; do
    # cowork-staging-lint --check-commit <sha>
    node harness-engineering/scripts/cowork-staging-lint.js --check-commit "$commit" > /dev/null 2>&1
    LINT_R=$?
    if [ $LINT_R -ne 0 ]; then
      echo ""
      echo "❌ pre-push 차단 — commit $commit 가 multi-module 위반"
      echo "   (CLAUDE.md 규칙 21 — Cowork 멀티 세션 staging 침범 방지)"
      echo ""
      # 상세 출력
      node harness-engineering/scripts/cowork-staging-lint.js --check-commit "$commit"
      EXIT_CODE=1
    fi
  done
done

if [ $EXIT_CODE -ne 0 ]; then
  echo ""
  echo "  조치 옵션:"
  echo "    1. 잘못된 commit 분리:"
  echo "       git reset --soft HEAD~N   # N = 잘못된 commit 개수"
  echo "       git status   # 자기 모듈 / 다른 모듈 분리 확인"
  echo "       자기 모듈만 git add → commit → push"
  echo ""
  echo "    2. 의도된 cross-module push (드물게):"
  echo "       COWORK_ALLOW_MULTI_MODULE=1 git push origin main"
  echo ""
  echo "  강제 우회 (절대 권장 X — 사용자 명시 결정 시만):"
  echo "    git push --no-verify"
  exit 1
fi

exit 0
`

const args = new Set(process.argv.slice(2))

function uninstallOne(hookPath, marker, label) {
  if (!fs.existsSync(hookPath)) {
    console.log(`[install-hook] ${label} hook 없음 — 제거할 것 없음`)
    return
  }
  const content = fs.readFileSync(hookPath, 'utf-8')
  if (!content.includes(marker)) {
    console.log(`[install-hook] ${label}: 다른 hook 설치됨 — 직접 제거 필요:`, hookPath)
    return
  }
  fs.unlinkSync(hookPath)
  console.log(`[install-hook] ✅ ${label} hook 제거 완료`)
}

function uninstall() {
  uninstallOne(HOOK_PATH, HOOK_MARKER, 'pre-commit')
  uninstallOne(PUSH_HOOK_PATH, PUSH_HOOK_MARKER, 'pre-push')
}

function installOne(hookPath, content, marker, label) {
  // 기존 hook 백업
  if (fs.existsSync(hookPath)) {
    const existing = fs.readFileSync(hookPath, 'utf-8')
    if (existing.includes(marker)) {
      console.log(`[install-hook] ${label}: 이미 설치됨 — 갱신`)
    } else {
      const backup = hookPath + '.backup-' + Date.now()
      fs.copyFileSync(hookPath, backup)
      console.log(`[install-hook] ${label}: 기존 hook 백업 → ${path.relative(ROOT, backup)}`)
    }
  }

  fs.writeFileSync(hookPath, content)
  fs.chmodSync(hookPath, 0o755)
  console.log(`[install-hook] ✅ ${label} hook 설치 → ${path.relative(ROOT, hookPath)}`)
}

function install() {
  // .git 디렉토리 존재 확인
  const gitDir = path.join(ROOT, '.git')
  if (!fs.existsSync(gitDir)) {
    console.error('[install-hook] ❌ .git 디렉토리 없음 — git 저장소가 아님')
    process.exit(1)
  }

  // PR-COWORK: hooksPath 자가 진단 (cowork 세션 오염 감지)
  const hpCheck = checkHooksPath()
  if (!hpCheck.ok) {
    console.warn('')
    console.warn('⚠ core.hooksPath 가 잘못 설정됨:')
    console.warn(`    현재: ${hpCheck.hooksPath}`)
    console.warn(`    기대: ${hpCheck.expected}`)
    console.warn('  → 다른 cowork 세션에서 오염되었을 가능성. 자동 수정 진행:')
    if (args.has('--no-fix-config')) {
      console.warn('  --no-fix-config 플래그 — 자가 수정 skip')
    } else {
      fixHooksPath()
    }
  } else {
    console.log('[install-hook] ✓ core.hooksPath 정상 (기본 .git/hooks 사용)')
  }

  installOne(HOOK_PATH, HOOK_CONTENT, HOOK_MARKER, 'pre-commit')
  installOne(PUSH_HOOK_PATH, PUSH_HOOK_CONTENT, PUSH_HOOK_MARKER, 'pre-push')

  console.log('')
  console.log('  매 commit 시: harness-lint (sql / sql-fn / api-trace / cowork-staging / 등)')
  console.log('  매 push 시:   pre-push — 새 commit 들 multi-module 위반 검사 (CLAUDE.md 규칙 21)')
  console.log('')
  console.log('  강제 우회:')
  console.log('    commit: git commit --no-verify  (권장 X — CLAUDE.md 규칙 21 금지)')
  console.log('    push:   COWORK_ALLOW_MULTI_MODULE=1 git push  (의도적 cross-module 시만)')
}

if (args.has('--uninstall')) uninstall()
else install()
